// Code generated by protoc-gen-go.
// source: bnet/protocol/game_master/game_master.proto
// DO NOT EDIT!

package bnet_protocol_game_master

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"
import bnet_protocol_attribute_468 "github.com/HearthSim/hs-proto-go/bnet/protocol/attribute_468"
import bnet_protocol "github.com/HearthSim/hs-proto-go/bnet/protocol"
import bnet_protocol_server_pool "github.com/HearthSim/hs-proto-go/bnet/protocol/server_pool"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// ref: bnet.protocol.game_master.FactoryUpdateNotification/Types/Operation
type FactoryUpdateNotification_Operation int32

const (
	FactoryUpdateNotification_ADD    FactoryUpdateNotification_Operation = 1
	FactoryUpdateNotification_REMOVE FactoryUpdateNotification_Operation = 2
	FactoryUpdateNotification_CHANGE FactoryUpdateNotification_Operation = 3
)

var FactoryUpdateNotification_Operation_name = map[int32]string{
	1: "ADD",
	2: "REMOVE",
	3: "CHANGE",
}
var FactoryUpdateNotification_Operation_value = map[string]int32{
	"ADD":    1,
	"REMOVE": 2,
	"CHANGE": 3,
}

func (x FactoryUpdateNotification_Operation) Enum() *FactoryUpdateNotification_Operation {
	p := new(FactoryUpdateNotification_Operation)
	*p = x
	return p
}
func (x FactoryUpdateNotification_Operation) String() string {
	return proto.EnumName(FactoryUpdateNotification_Operation_name, int32(x))
}
func (x FactoryUpdateNotification_Operation) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *FactoryUpdateNotification_Operation) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FactoryUpdateNotification_Operation_value, data, "FactoryUpdateNotification_Operation")
	if err != nil {
		return err
	}
	*x = FactoryUpdateNotification_Operation(value)
	return nil
}

// ref: bnet.protocol.game_master.CancelGameEntryRequest
type CancelGameEntryRequest struct {
	RequestId        *uint64   `protobuf:"fixed64,1,req,name=request_id" json:"request_id,omitempty"`
	FactoryId        *uint64   `protobuf:"fixed64,2,opt,name=factory_id" json:"factory_id,omitempty"`
	Player           []*Player `protobuf:"bytes,3,rep,name=player" json:"player,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *CancelGameEntryRequest) Reset()         { *m = CancelGameEntryRequest{} }
func (m *CancelGameEntryRequest) String() string { return proto.CompactTextString(m) }
func (*CancelGameEntryRequest) ProtoMessage()    {}

func (m *CancelGameEntryRequest) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *CancelGameEntryRequest) GetFactoryId() uint64 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

func (m *CancelGameEntryRequest) GetPlayer() []*Player {
	if m != nil {
		return m.Player
	}
	return nil
}

// ref: bnet.protocol.game_master.ChangeGameRequest
type ChangeGameRequest struct {
	GameHandle       *GameHandle                `protobuf:"bytes,1,req,name=game_handle" json:"game_handle,omitempty"`
	Open             *bool                      `protobuf:"varint,2,opt,name=open" json:"open,omitempty"`
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,3,rep,name=attribute" json:"attribute,omitempty"`
	Replace          *bool                      `protobuf:"varint,4,opt,name=replace,def=0" json:"replace,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ChangeGameRequest) Reset()         { *m = ChangeGameRequest{} }
func (m *ChangeGameRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeGameRequest) ProtoMessage()    {}

const Default_ChangeGameRequest_Replace bool = false

func (m *ChangeGameRequest) GetGameHandle() *GameHandle {
	if m != nil {
		return m.GameHandle
	}
	return nil
}

func (m *ChangeGameRequest) GetOpen() bool {
	if m != nil && m.Open != nil {
		return *m.Open
	}
	return false
}

func (m *ChangeGameRequest) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *ChangeGameRequest) GetReplace() bool {
	if m != nil && m.Replace != nil {
		return *m.Replace
	}
	return Default_ChangeGameRequest_Replace
}

// ref: bnet.protocol.game_master.ConnectInfo
type ConnectInfo struct {
	MemberId         *bnet_protocol.EntityId    `protobuf:"bytes,1,req,name=member_id" json:"member_id,omitempty"`
	Host             *string                    `protobuf:"bytes,2,req,name=host" json:"host,omitempty"`
	Port             *int32                     `protobuf:"varint,3,req,name=port" json:"port,omitempty"`
	Token            []byte                     `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,5,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *ConnectInfo) Reset()         { *m = ConnectInfo{} }
func (m *ConnectInfo) String() string { return proto.CompactTextString(m) }
func (*ConnectInfo) ProtoMessage()    {}

func (m *ConnectInfo) GetMemberId() *bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *ConnectInfo) GetHost() string {
	if m != nil && m.Host != nil {
		return *m.Host
	}
	return ""
}

func (m *ConnectInfo) GetPort() int32 {
	if m != nil && m.Port != nil {
		return *m.Port
	}
	return 0
}

func (m *ConnectInfo) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func (m *ConnectInfo) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

// ref: bnet.protocol.game_master.FactoryUpdateNotification
type FactoryUpdateNotification struct {
	Op               *FactoryUpdateNotification_Operation `protobuf:"varint,1,req,name=op,enum=bnet.protocol.game_master.FactoryUpdateNotification_Operation" json:"op,omitempty"`
	Description      *GameFactoryDescription              `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	ProgramId        *uint32                              `protobuf:"fixed32,3,opt,name=program_id" json:"program_id,omitempty"`
	XXX_unrecognized []byte                               `json:"-"`
}

func (m *FactoryUpdateNotification) Reset()         { *m = FactoryUpdateNotification{} }
func (m *FactoryUpdateNotification) String() string { return proto.CompactTextString(m) }
func (*FactoryUpdateNotification) ProtoMessage()    {}

func (m *FactoryUpdateNotification) GetOp() FactoryUpdateNotification_Operation {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return 0
}

func (m *FactoryUpdateNotification) GetDescription() *GameFactoryDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *FactoryUpdateNotification) GetProgramId() uint32 {
	if m != nil && m.ProgramId != nil {
		return *m.ProgramId
	}
	return 0
}

// ref: bnet.protocol.game_master.FindGameRequest
type FindGameRequest struct {
	Player               []*Player       `protobuf:"bytes,1,rep,name=player" json:"player,omitempty"`
	FactoryId            *uint64         `protobuf:"fixed64,2,opt,name=factory_id" json:"factory_id,omitempty"`
	Properties           *GameProperties `protobuf:"bytes,3,opt,name=properties" json:"properties,omitempty"`
	ObjectId             *uint64         `protobuf:"varint,4,opt,name=object_id" json:"object_id,omitempty"`
	RequestId            *uint64         `protobuf:"fixed64,5,opt,name=request_id" json:"request_id,omitempty"`
	AdvancedNotification *bool           `protobuf:"varint,6,opt,name=advanced_notification,def=0" json:"advanced_notification,omitempty"`
	XXX_unrecognized     []byte          `json:"-"`
}

func (m *FindGameRequest) Reset()         { *m = FindGameRequest{} }
func (m *FindGameRequest) String() string { return proto.CompactTextString(m) }
func (*FindGameRequest) ProtoMessage()    {}

const Default_FindGameRequest_AdvancedNotification bool = false

func (m *FindGameRequest) GetPlayer() []*Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *FindGameRequest) GetFactoryId() uint64 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

func (m *FindGameRequest) GetProperties() *GameProperties {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *FindGameRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *FindGameRequest) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *FindGameRequest) GetAdvancedNotification() bool {
	if m != nil && m.AdvancedNotification != nil {
		return *m.AdvancedNotification
	}
	return Default_FindGameRequest_AdvancedNotification
}

// ref: bnet.protocol.game_master.FindGameResponse
type FindGameResponse struct {
	RequestId        *uint64 `protobuf:"fixed64,1,opt,name=request_id" json:"request_id,omitempty"`
	FactoryId        *uint64 `protobuf:"fixed64,2,opt,name=factory_id" json:"factory_id,omitempty"`
	Queued           *bool   `protobuf:"varint,3,opt,name=queued,def=0" json:"queued,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *FindGameResponse) Reset()         { *m = FindGameResponse{} }
func (m *FindGameResponse) String() string { return proto.CompactTextString(m) }
func (*FindGameResponse) ProtoMessage()    {}

const Default_FindGameResponse_Queued bool = false

func (m *FindGameResponse) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *FindGameResponse) GetFactoryId() uint64 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

func (m *FindGameResponse) GetQueued() bool {
	if m != nil && m.Queued != nil {
		return *m.Queued
	}
	return Default_FindGameResponse_Queued
}

// ref: bnet.protocol.game_master.GameEndedNotification
type GameEndedNotification struct {
	GameHandle       *GameHandle `protobuf:"bytes,1,req,name=game_handle" json:"game_handle,omitempty"`
	Reason           *uint32     `protobuf:"varint,2,opt,name=reason,def=0" json:"reason,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GameEndedNotification) Reset()         { *m = GameEndedNotification{} }
func (m *GameEndedNotification) String() string { return proto.CompactTextString(m) }
func (*GameEndedNotification) ProtoMessage()    {}

const Default_GameEndedNotification_Reason uint32 = 0

func (m *GameEndedNotification) GetGameHandle() *GameHandle {
	if m != nil {
		return m.GameHandle
	}
	return nil
}

func (m *GameEndedNotification) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return Default_GameEndedNotification_Reason
}

// ref: bnet.protocol.game_master.GameFactoryDescription
type GameFactoryDescription struct {
	Id               *uint64                    `protobuf:"fixed64,1,req,name=id" json:"id,omitempty"`
	Name             *string                    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,3,rep,name=attribute" json:"attribute,omitempty"`
	StatsBucket      []*GameStatsBucket         `protobuf:"bytes,4,rep,name=stats_bucket" json:"stats_bucket,omitempty"`
	UnseededId       *uint64                    `protobuf:"fixed64,5,opt,name=unseeded_id,def=0" json:"unseeded_id,omitempty"`
	AllowQueueing    *bool                      `protobuf:"varint,6,opt,name=allow_queueing,def=1" json:"allow_queueing,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *GameFactoryDescription) Reset()         { *m = GameFactoryDescription{} }
func (m *GameFactoryDescription) String() string { return proto.CompactTextString(m) }
func (*GameFactoryDescription) ProtoMessage()    {}

const Default_GameFactoryDescription_UnseededId uint64 = 0
const Default_GameFactoryDescription_AllowQueueing bool = true

func (m *GameFactoryDescription) GetId() uint64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *GameFactoryDescription) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *GameFactoryDescription) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *GameFactoryDescription) GetStatsBucket() []*GameStatsBucket {
	if m != nil {
		return m.StatsBucket
	}
	return nil
}

func (m *GameFactoryDescription) GetUnseededId() uint64 {
	if m != nil && m.UnseededId != nil {
		return *m.UnseededId
	}
	return Default_GameFactoryDescription_UnseededId
}

func (m *GameFactoryDescription) GetAllowQueueing() bool {
	if m != nil && m.AllowQueueing != nil {
		return *m.AllowQueueing
	}
	return Default_GameFactoryDescription_AllowQueueing
}

// ref: bnet.protocol.game_master.GameFoundNotification
type GameFoundNotification struct {
	RequestId        *uint64        `protobuf:"fixed64,1,req,name=request_id" json:"request_id,omitempty"`
	ErrorCode        *uint32        `protobuf:"varint,2,opt,name=error_code,def=0" json:"error_code,omitempty"`
	GameHandle       *GameHandle    `protobuf:"bytes,3,opt,name=game_handle" json:"game_handle,omitempty"`
	ConnectInfo      []*ConnectInfo `protobuf:"bytes,4,rep,name=connect_info" json:"connect_info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *GameFoundNotification) Reset()         { *m = GameFoundNotification{} }
func (m *GameFoundNotification) String() string { return proto.CompactTextString(m) }
func (*GameFoundNotification) ProtoMessage()    {}

const Default_GameFoundNotification_ErrorCode uint32 = 0

func (m *GameFoundNotification) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *GameFoundNotification) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return Default_GameFoundNotification_ErrorCode
}

func (m *GameFoundNotification) GetGameHandle() *GameHandle {
	if m != nil {
		return m.GameHandle
	}
	return nil
}

func (m *GameFoundNotification) GetConnectInfo() []*ConnectInfo {
	if m != nil {
		return m.ConnectInfo
	}
	return nil
}

// ref: bnet.protocol.game_master.GameHandle
type GameHandle struct {
	FactoryId        *uint64                 `protobuf:"fixed64,1,req,name=factory_id" json:"factory_id,omitempty"`
	GameId           *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=game_id" json:"game_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GameHandle) Reset()         { *m = GameHandle{} }
func (m *GameHandle) String() string { return proto.CompactTextString(m) }
func (*GameHandle) ProtoMessage()    {}

func (m *GameHandle) GetFactoryId() uint64 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

func (m *GameHandle) GetGameId() *bnet_protocol.EntityId {
	if m != nil {
		return m.GameId
	}
	return nil
}

// ref: bnet.protocol.game_master.GameProperties
type GameProperties struct {
	CreationAttributes []*bnet_protocol.Attribute                   `protobuf:"bytes,1,rep,name=creation_attributes" json:"creation_attributes,omitempty"`
	Filter             *bnet_protocol_attribute_468.AttributeFilter `protobuf:"bytes,2,opt,name=filter" json:"filter,omitempty"`
	Create             *bool                                        `protobuf:"varint,3,opt,name=create,def=0" json:"create,omitempty"`
	Open               *bool                                        `protobuf:"varint,4,opt,name=open,def=1" json:"open,omitempty"`
	ProgramId          *uint32                                      `protobuf:"fixed32,5,opt,name=program_id" json:"program_id,omitempty"`
	XXX_unrecognized   []byte                                       `json:"-"`
}

func (m *GameProperties) Reset()         { *m = GameProperties{} }
func (m *GameProperties) String() string { return proto.CompactTextString(m) }
func (*GameProperties) ProtoMessage()    {}

const Default_GameProperties_Create bool = false
const Default_GameProperties_Open bool = true

func (m *GameProperties) GetCreationAttributes() []*bnet_protocol.Attribute {
	if m != nil {
		return m.CreationAttributes
	}
	return nil
}

func (m *GameProperties) GetFilter() *bnet_protocol_attribute_468.AttributeFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *GameProperties) GetCreate() bool {
	if m != nil && m.Create != nil {
		return *m.Create
	}
	return Default_GameProperties_Create
}

func (m *GameProperties) GetOpen() bool {
	if m != nil && m.Open != nil {
		return *m.Open
	}
	return Default_GameProperties_Open
}

func (m *GameProperties) GetProgramId() uint32 {
	if m != nil && m.ProgramId != nil {
		return *m.ProgramId
	}
	return 0
}

// ref: bnet.protocol.game_master.GameStatsBucket
type GameStatsBucket struct {
	BucketMin                  *float32 `protobuf:"fixed32,1,opt,name=bucket_min,def=0" json:"bucket_min,omitempty"`
	BucketMax                  *float32 `protobuf:"fixed32,2,opt,name=bucket_max,def=4.294967e+09" json:"bucket_max,omitempty"`
	WaitMilliseconds           *uint32  `protobuf:"varint,3,opt,name=wait_milliseconds,def=0" json:"wait_milliseconds,omitempty"`
	GamesPerHour               *uint32  `protobuf:"varint,4,opt,name=games_per_hour,def=0" json:"games_per_hour,omitempty"`
	ActiveGames                *uint32  `protobuf:"varint,5,opt,name=active_games,def=0" json:"active_games,omitempty"`
	ActivePlayers              *uint32  `protobuf:"varint,6,opt,name=active_players,def=0" json:"active_players,omitempty"`
	FormingGames               *uint32  `protobuf:"varint,7,opt,name=forming_games,def=0" json:"forming_games,omitempty"`
	WaitingPlayers             *uint32  `protobuf:"varint,8,opt,name=waiting_players,def=0" json:"waiting_players,omitempty"`
	OpenJoinableGames          *uint32  `protobuf:"varint,9,opt,name=open_joinable_games,def=0" json:"open_joinable_games,omitempty"`
	PlayersInOpenJoinableGames *uint32  `protobuf:"varint,10,opt,name=players_in_open_joinable_games,def=0" json:"players_in_open_joinable_games,omitempty"`
	OpenGamesTotal             *uint32  `protobuf:"varint,11,opt,name=open_games_total,def=0" json:"open_games_total,omitempty"`
	PlayersInOpenGamesTotal    *uint32  `protobuf:"varint,12,opt,name=players_in_open_games_total,def=0" json:"players_in_open_games_total,omitempty"`
	XXX_unrecognized           []byte   `json:"-"`
}

func (m *GameStatsBucket) Reset()         { *m = GameStatsBucket{} }
func (m *GameStatsBucket) String() string { return proto.CompactTextString(m) }
func (*GameStatsBucket) ProtoMessage()    {}

const Default_GameStatsBucket_BucketMin float32 = 0
const Default_GameStatsBucket_BucketMax float32 = 4.294967e+09
const Default_GameStatsBucket_WaitMilliseconds uint32 = 0
const Default_GameStatsBucket_GamesPerHour uint32 = 0
const Default_GameStatsBucket_ActiveGames uint32 = 0
const Default_GameStatsBucket_ActivePlayers uint32 = 0
const Default_GameStatsBucket_FormingGames uint32 = 0
const Default_GameStatsBucket_WaitingPlayers uint32 = 0
const Default_GameStatsBucket_OpenJoinableGames uint32 = 0
const Default_GameStatsBucket_PlayersInOpenJoinableGames uint32 = 0
const Default_GameStatsBucket_OpenGamesTotal uint32 = 0
const Default_GameStatsBucket_PlayersInOpenGamesTotal uint32 = 0

func (m *GameStatsBucket) GetBucketMin() float32 {
	if m != nil && m.BucketMin != nil {
		return *m.BucketMin
	}
	return Default_GameStatsBucket_BucketMin
}

func (m *GameStatsBucket) GetBucketMax() float32 {
	if m != nil && m.BucketMax != nil {
		return *m.BucketMax
	}
	return Default_GameStatsBucket_BucketMax
}

func (m *GameStatsBucket) GetWaitMilliseconds() uint32 {
	if m != nil && m.WaitMilliseconds != nil {
		return *m.WaitMilliseconds
	}
	return Default_GameStatsBucket_WaitMilliseconds
}

func (m *GameStatsBucket) GetGamesPerHour() uint32 {
	if m != nil && m.GamesPerHour != nil {
		return *m.GamesPerHour
	}
	return Default_GameStatsBucket_GamesPerHour
}

func (m *GameStatsBucket) GetActiveGames() uint32 {
	if m != nil && m.ActiveGames != nil {
		return *m.ActiveGames
	}
	return Default_GameStatsBucket_ActiveGames
}

func (m *GameStatsBucket) GetActivePlayers() uint32 {
	if m != nil && m.ActivePlayers != nil {
		return *m.ActivePlayers
	}
	return Default_GameStatsBucket_ActivePlayers
}

func (m *GameStatsBucket) GetFormingGames() uint32 {
	if m != nil && m.FormingGames != nil {
		return *m.FormingGames
	}
	return Default_GameStatsBucket_FormingGames
}

func (m *GameStatsBucket) GetWaitingPlayers() uint32 {
	if m != nil && m.WaitingPlayers != nil {
		return *m.WaitingPlayers
	}
	return Default_GameStatsBucket_WaitingPlayers
}

func (m *GameStatsBucket) GetOpenJoinableGames() uint32 {
	if m != nil && m.OpenJoinableGames != nil {
		return *m.OpenJoinableGames
	}
	return Default_GameStatsBucket_OpenJoinableGames
}

func (m *GameStatsBucket) GetPlayersInOpenJoinableGames() uint32 {
	if m != nil && m.PlayersInOpenJoinableGames != nil {
		return *m.PlayersInOpenJoinableGames
	}
	return Default_GameStatsBucket_PlayersInOpenJoinableGames
}

func (m *GameStatsBucket) GetOpenGamesTotal() uint32 {
	if m != nil && m.OpenGamesTotal != nil {
		return *m.OpenGamesTotal
	}
	return Default_GameStatsBucket_OpenGamesTotal
}

func (m *GameStatsBucket) GetPlayersInOpenGamesTotal() uint32 {
	if m != nil && m.PlayersInOpenGamesTotal != nil {
		return *m.PlayersInOpenGamesTotal
	}
	return Default_GameStatsBucket_PlayersInOpenGamesTotal
}

// ref: bnet.protocol.game_master.GetFactoryInfoRequest
type GetFactoryInfoRequest struct {
	FactoryId        *uint64 `protobuf:"fixed64,1,req,name=factory_id" json:"factory_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetFactoryInfoRequest) Reset()         { *m = GetFactoryInfoRequest{} }
func (m *GetFactoryInfoRequest) String() string { return proto.CompactTextString(m) }
func (*GetFactoryInfoRequest) ProtoMessage()    {}

func (m *GetFactoryInfoRequest) GetFactoryId() uint64 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

// ref: bnet.protocol.game_master.GetFactoryInfoResponse
type GetFactoryInfoResponse struct {
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	StatsBucket      []*GameStatsBucket         `protobuf:"bytes,2,rep,name=stats_bucket" json:"stats_bucket,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *GetFactoryInfoResponse) Reset()         { *m = GetFactoryInfoResponse{} }
func (m *GetFactoryInfoResponse) String() string { return proto.CompactTextString(m) }
func (*GetFactoryInfoResponse) ProtoMessage()    {}

func (m *GetFactoryInfoResponse) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *GetFactoryInfoResponse) GetStatsBucket() []*GameStatsBucket {
	if m != nil {
		return m.StatsBucket
	}
	return nil
}

// ref: bnet.protocol.game_master.GetGameStatsRequest
type GetGameStatsRequest struct {
	FactoryId        *uint64                                      `protobuf:"fixed64,1,req,name=factory_id" json:"factory_id,omitempty"`
	Filter           *bnet_protocol_attribute_468.AttributeFilter `protobuf:"bytes,2,req,name=filter" json:"filter,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *GetGameStatsRequest) Reset()         { *m = GetGameStatsRequest{} }
func (m *GetGameStatsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGameStatsRequest) ProtoMessage()    {}

func (m *GetGameStatsRequest) GetFactoryId() uint64 {
	if m != nil && m.FactoryId != nil {
		return *m.FactoryId
	}
	return 0
}

func (m *GetGameStatsRequest) GetFilter() *bnet_protocol_attribute_468.AttributeFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

// ref: bnet.protocol.game_master.GetGameStatsResponse
type GetGameStatsResponse struct {
	StatsBucket      []*GameStatsBucket `protobuf:"bytes,1,rep,name=stats_bucket" json:"stats_bucket,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GetGameStatsResponse) Reset()         { *m = GetGameStatsResponse{} }
func (m *GetGameStatsResponse) String() string { return proto.CompactTextString(m) }
func (*GetGameStatsResponse) ProtoMessage()    {}

func (m *GetGameStatsResponse) GetStatsBucket() []*GameStatsBucket {
	if m != nil {
		return m.StatsBucket
	}
	return nil
}

// ref: bnet.protocol.game_master.JoinGameRequest
type JoinGameRequest struct {
	GameHandle           *GameHandle `protobuf:"bytes,1,req,name=game_handle" json:"game_handle,omitempty"`
	Player               []*Player   `protobuf:"bytes,2,rep,name=player" json:"player,omitempty"`
	AdvancedNotification *bool       `protobuf:"varint,3,opt,name=advanced_notification,def=0" json:"advanced_notification,omitempty"`
	XXX_unrecognized     []byte      `json:"-"`
}

func (m *JoinGameRequest) Reset()         { *m = JoinGameRequest{} }
func (m *JoinGameRequest) String() string { return proto.CompactTextString(m) }
func (*JoinGameRequest) ProtoMessage()    {}

const Default_JoinGameRequest_AdvancedNotification bool = false

func (m *JoinGameRequest) GetGameHandle() *GameHandle {
	if m != nil {
		return m.GameHandle
	}
	return nil
}

func (m *JoinGameRequest) GetPlayer() []*Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *JoinGameRequest) GetAdvancedNotification() bool {
	if m != nil && m.AdvancedNotification != nil {
		return *m.AdvancedNotification
	}
	return Default_JoinGameRequest_AdvancedNotification
}

// ref: bnet.protocol.game_master.JoinGameResponse
type JoinGameResponse struct {
	RequestId        *uint64        `protobuf:"fixed64,1,opt,name=request_id" json:"request_id,omitempty"`
	Queued           *bool          `protobuf:"varint,2,opt,name=queued,def=0" json:"queued,omitempty"`
	ConnectInfo      []*ConnectInfo `protobuf:"bytes,3,rep,name=connect_info" json:"connect_info,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *JoinGameResponse) Reset()         { *m = JoinGameResponse{} }
func (m *JoinGameResponse) String() string { return proto.CompactTextString(m) }
func (*JoinGameResponse) ProtoMessage()    {}

const Default_JoinGameResponse_Queued bool = false

func (m *JoinGameResponse) GetRequestId() uint64 {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return 0
}

func (m *JoinGameResponse) GetQueued() bool {
	if m != nil && m.Queued != nil {
		return *m.Queued
	}
	return Default_JoinGameResponse_Queued
}

func (m *JoinGameResponse) GetConnectInfo() []*ConnectInfo {
	if m != nil {
		return m.ConnectInfo
	}
	return nil
}

// ref: bnet.protocol.game_master.ListFactoriesRequest
type ListFactoriesRequest struct {
	Filter           *bnet_protocol_attribute_468.AttributeFilter `protobuf:"bytes,1,req,name=filter" json:"filter,omitempty"`
	StartIndex       *uint32                                      `protobuf:"varint,2,opt,name=start_index,def=0" json:"start_index,omitempty"`
	MaxResults       *uint32                                      `protobuf:"varint,3,opt,name=max_results,def=100" json:"max_results,omitempty"`
	XXX_unrecognized []byte                                       `json:"-"`
}

func (m *ListFactoriesRequest) Reset()         { *m = ListFactoriesRequest{} }
func (m *ListFactoriesRequest) String() string { return proto.CompactTextString(m) }
func (*ListFactoriesRequest) ProtoMessage()    {}

const Default_ListFactoriesRequest_StartIndex uint32 = 0
const Default_ListFactoriesRequest_MaxResults uint32 = 100

func (m *ListFactoriesRequest) GetFilter() *bnet_protocol_attribute_468.AttributeFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListFactoriesRequest) GetStartIndex() uint32 {
	if m != nil && m.StartIndex != nil {
		return *m.StartIndex
	}
	return Default_ListFactoriesRequest_StartIndex
}

func (m *ListFactoriesRequest) GetMaxResults() uint32 {
	if m != nil && m.MaxResults != nil {
		return *m.MaxResults
	}
	return Default_ListFactoriesRequest_MaxResults
}

// ref: bnet.protocol.game_master.ListFactoriesResponse
type ListFactoriesResponse struct {
	Description      []*GameFactoryDescription `protobuf:"bytes,1,rep,name=description" json:"description,omitempty"`
	TotalResults     *uint32                   `protobuf:"varint,2,opt,name=total_results" json:"total_results,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *ListFactoriesResponse) Reset()         { *m = ListFactoriesResponse{} }
func (m *ListFactoriesResponse) String() string { return proto.CompactTextString(m) }
func (*ListFactoriesResponse) ProtoMessage()    {}

func (m *ListFactoriesResponse) GetDescription() []*GameFactoryDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ListFactoriesResponse) GetTotalResults() uint32 {
	if m != nil && m.TotalResults != nil {
		return *m.TotalResults
	}
	return 0
}

// ref: bnet.protocol.game_master.Player
type Player struct {
	Identity         *bnet_protocol.Identity    `protobuf:"bytes,1,opt,name=identity" json:"identity,omitempty"`
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}

func (m *Player) GetIdentity() *bnet_protocol.Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Player) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

// ref: bnet.protocol.game_master.PlayerLeftNotification
type PlayerLeftNotification struct {
	GameHandle       *GameHandle             `protobuf:"bytes,1,req,name=game_handle" json:"game_handle,omitempty"`
	MemberId         *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=member_id" json:"member_id,omitempty"`
	Reason           *uint32                 `protobuf:"varint,3,opt,name=reason,def=1" json:"reason,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *PlayerLeftNotification) Reset()         { *m = PlayerLeftNotification{} }
func (m *PlayerLeftNotification) String() string { return proto.CompactTextString(m) }
func (*PlayerLeftNotification) ProtoMessage()    {}

const Default_PlayerLeftNotification_Reason uint32 = 1

func (m *PlayerLeftNotification) GetGameHandle() *GameHandle {
	if m != nil {
		return m.GameHandle
	}
	return nil
}

func (m *PlayerLeftNotification) GetMemberId() *bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *PlayerLeftNotification) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return Default_PlayerLeftNotification_Reason
}

// ref: bnet.protocol.game_master.RegisterServerRequest
type RegisterServerRequest struct {
	Attribute        []*bnet_protocol.Attribute             `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	State            *bnet_protocol_server_pool.ServerState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	ProgramId        *uint32                                `protobuf:"fixed32,3,req,name=program_id" json:"program_id,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *RegisterServerRequest) Reset()         { *m = RegisterServerRequest{} }
func (m *RegisterServerRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterServerRequest) ProtoMessage()    {}

func (m *RegisterServerRequest) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *RegisterServerRequest) GetState() *bnet_protocol_server_pool.ServerState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *RegisterServerRequest) GetProgramId() uint32 {
	if m != nil && m.ProgramId != nil {
		return *m.ProgramId
	}
	return 0
}

// ref: bnet.protocol.game_master.RegisterUtilitiesRequest
type RegisterUtilitiesRequest struct {
	Attribute        []*bnet_protocol.Attribute             `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	State            *bnet_protocol_server_pool.ServerState `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	ProgramId        *uint32                                `protobuf:"fixed32,3,req,name=program_id" json:"program_id,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (m *RegisterUtilitiesRequest) Reset()         { *m = RegisterUtilitiesRequest{} }
func (m *RegisterUtilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterUtilitiesRequest) ProtoMessage()    {}

func (m *RegisterUtilitiesRequest) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *RegisterUtilitiesRequest) GetState() *bnet_protocol_server_pool.ServerState {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *RegisterUtilitiesRequest) GetProgramId() uint32 {
	if m != nil && m.ProgramId != nil {
		return *m.ProgramId
	}
	return 0
}

// ref: bnet.protocol.game_master.SubscribeRequest
type SubscribeRequest struct {
	ObjectId         *uint64 `protobuf:"varint,1,req,name=object_id" json:"object_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}

func (m *SubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

// ref: bnet.protocol.game_master.SubscribeResponse
type SubscribeResponse struct {
	SubscriptionId   *uint64 `protobuf:"varint,1,opt,name=subscription_id" json:"subscription_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubscribeResponse) Reset()         { *m = SubscribeResponse{} }
func (m *SubscribeResponse) String() string { return proto.CompactTextString(m) }
func (*SubscribeResponse) ProtoMessage()    {}

func (m *SubscribeResponse) GetSubscriptionId() uint64 {
	if m != nil && m.SubscriptionId != nil {
		return *m.SubscriptionId
	}
	return 0
}

// ref: bnet.protocol.game_master.UnregisterServerRequest
type UnregisterServerRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnregisterServerRequest) Reset()         { *m = UnregisterServerRequest{} }
func (m *UnregisterServerRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterServerRequest) ProtoMessage()    {}

// ref: bnet.protocol.game_master.UnregisterUtilitiesRequest
type UnregisterUtilitiesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *UnregisterUtilitiesRequest) Reset()         { *m = UnregisterUtilitiesRequest{} }
func (m *UnregisterUtilitiesRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterUtilitiesRequest) ProtoMessage()    {}

// ref: bnet.protocol.game_master.UnsubscribeRequest
type UnsubscribeRequest struct {
	SubscriptionId   *uint64 `protobuf:"varint,1,req,name=subscription_id" json:"subscription_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}

func (m *UnsubscribeRequest) GetSubscriptionId() uint64 {
	if m != nil && m.SubscriptionId != nil {
		return *m.SubscriptionId
	}
	return 0
}

func init() {
	proto.RegisterEnum("bnet.protocol.game_master.FactoryUpdateNotification_Operation", FactoryUpdateNotification_Operation_name, FactoryUpdateNotification_Operation_value)
}
