// Code generated by protoc-gen-go.
// source: github.com/HearthSim/hs-proto-go/bnet/profanity/profanity.proto
// DO NOT EDIT!

/*
Package profanity is a generated protocol buffer package.

It is generated from these files:
	github.com/HearthSim/hs-proto-go/bnet/profanity/profanity.proto

It has these top-level messages:
	WordFilter
	WordFilters
*/
package profanity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WordFilter struct {
	Type             *string `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Regex            *string `protobuf:"bytes,2,req,name=regex" json:"regex,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *WordFilter) Reset()                    { *m = WordFilter{} }
func (m *WordFilter) String() string            { return proto.CompactTextString(m) }
func (*WordFilter) ProtoMessage()               {}
func (*WordFilter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *WordFilter) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *WordFilter) GetRegex() string {
	if m != nil && m.Regex != nil {
		return *m.Regex
	}
	return ""
}

type WordFilters struct {
	Filters          []*WordFilter `protobuf:"bytes,1,rep,name=filters" json:"filters,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *WordFilters) Reset()                    { *m = WordFilters{} }
func (m *WordFilters) String() string            { return proto.CompactTextString(m) }
func (*WordFilters) ProtoMessage()               {}
func (*WordFilters) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WordFilters) GetFilters() []*WordFilter {
	if m != nil {
		return m.Filters
	}
	return nil
}

func init() {
	proto.RegisterType((*WordFilter)(nil), "profanity.WordFilter")
	proto.RegisterType((*WordFilters)(nil), "profanity.WordFilters")
}

func init() {
	proto.RegisterFile("github.com/HearthSim/hs-proto-go/bnet/profanity/profanity.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xf7, 0x48, 0x4d, 0x2c, 0x2a, 0xc9, 0x08, 0xce, 0xcc,
	0xd5, 0xcf, 0x28, 0xd6, 0x2d, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x4d, 0xcf, 0xd7, 0x4f, 0xca, 0x4b,
	0x2d, 0xd1, 0x2f, 0x28, 0xca, 0x4f, 0x4b, 0xcc, 0xcb, 0x2c, 0xa9, 0x44, 0xb0, 0xf4, 0xc0, 0x2a,
	0x84, 0x38, 0xe1, 0x02, 0x4a, 0x66, 0x5c, 0x5c, 0xe1, 0xf9, 0x45, 0x29, 0x6e, 0x99, 0x39, 0x25,
	0xa9, 0x45, 0x42, 0x42, 0x5c, 0x2c, 0x25, 0x95, 0x05, 0xa9, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0x9c,
	0x41, 0x60, 0xb6, 0x90, 0x08, 0x17, 0x6b, 0x51, 0x6a, 0x7a, 0x6a, 0x85, 0x04, 0x13, 0x58, 0x10,
	0xc2, 0x51, 0xb2, 0xe3, 0xe2, 0x46, 0xe8, 0x2b, 0x16, 0xd2, 0xe7, 0x62, 0x4f, 0x83, 0x30, 0x25,
	0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x44, 0xf5, 0x10, 0x96, 0x22, 0x14, 0x06, 0xc1, 0x54, 0x01,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xed, 0x75, 0xaf, 0x0c, 0xc4, 0x00, 0x00, 0x00,
}
