// Code generated by protoc-gen-go.
// source: github.com/HearthSim/hs-proto-go/bnet/friends_types/friends_types.proto
// DO NOT EDIT!

/*
Package friends_types is a generated protocol buffer package.

It is generated from these files:
	github.com/HearthSim/hs-proto-go/bnet/friends_types/friends_types.proto

It has these top-level messages:
	Friend
	FriendInvitation
	FriendInvitationParams
*/
package friends_types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import attribute "github.com/HearthSim/hs-proto-go/bnet/attribute"
import entity "github.com/HearthSim/hs-proto-go/bnet/entity"
import invitation_types "github.com/HearthSim/hs-proto-go/bnet/invitation_types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Friend struct {
	Id               *entity.EntityId       `protobuf:"bytes,1,req,name=id" json:"id,omitempty"`
	Attribute        []*attribute.Attribute `protobuf:"bytes,2,rep,name=attribute" json:"attribute,omitempty"`
	Role             []uint32               `protobuf:"varint,3,rep,packed,name=role" json:"role,omitempty"`
	Privileges       *uint64                `protobuf:"varint,4,opt,name=privileges,def=0" json:"privileges,omitempty"`
	AttributesEpoch  *uint64                `protobuf:"varint,5,opt,name=attributes_epoch" json:"attributes_epoch,omitempty"`
	FullName         *string                `protobuf:"bytes,6,opt,name=full_name" json:"full_name,omitempty"`
	BattleTag        *string                `protobuf:"bytes,7,opt,name=battle_tag" json:"battle_tag,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Friend) Reset()                    { *m = Friend{} }
func (m *Friend) String() string            { return proto.CompactTextString(m) }
func (*Friend) ProtoMessage()               {}
func (*Friend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Friend_Privileges uint64 = 0

func (m *Friend) GetId() *entity.EntityId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Friend) GetAttribute() []*attribute.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Friend) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *Friend) GetPrivileges() uint64 {
	if m != nil && m.Privileges != nil {
		return *m.Privileges
	}
	return Default_Friend_Privileges
}

func (m *Friend) GetAttributesEpoch() uint64 {
	if m != nil && m.AttributesEpoch != nil {
		return *m.AttributesEpoch
	}
	return 0
}

func (m *Friend) GetFullName() string {
	if m != nil && m.FullName != nil {
		return *m.FullName
	}
	return ""
}

func (m *Friend) GetBattleTag() string {
	if m != nil && m.BattleTag != nil {
		return *m.BattleTag
	}
	return ""
}

type FriendInvitation struct {
	FirstReceived    *bool    `protobuf:"varint,1,opt,name=first_received,def=0" json:"first_received,omitempty"`
	Role             []uint32 `protobuf:"varint,2,rep,packed,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *FriendInvitation) Reset()                    { *m = FriendInvitation{} }
func (m *FriendInvitation) String() string            { return proto.CompactTextString(m) }
func (*FriendInvitation) ProtoMessage()               {}
func (*FriendInvitation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

const Default_FriendInvitation_FirstReceived bool = false

func (m *FriendInvitation) GetFirstReceived() bool {
	if m != nil && m.FirstReceived != nil {
		return *m.FirstReceived
	}
	return Default_FriendInvitation_FirstReceived
}

func (m *FriendInvitation) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

var E_FriendInvitation_FriendInvite = &proto.ExtensionDesc{
	ExtendedType:  (*invitation_types.Invitation)(nil),
	ExtensionType: (*FriendInvitation)(nil),
	Field:         103,
	Name:          "friends_types.FriendInvitation.friend_invite",
	Tag:           "bytes,103,opt,name=friend_invite",
}

type FriendInvitationParams struct {
	TargetEmail        *string  `protobuf:"bytes,1,opt,name=target_email" json:"target_email,omitempty"`
	TargetBattleTag    *string  `protobuf:"bytes,2,opt,name=target_battle_tag" json:"target_battle_tag,omitempty"`
	InviterBattleTag   *string  `protobuf:"bytes,3,opt,name=inviter_battle_tag" json:"inviter_battle_tag,omitempty"`
	InviterFullName    *string  `protobuf:"bytes,4,opt,name=inviter_full_name" json:"inviter_full_name,omitempty"`
	InviteeDisplayName *string  `protobuf:"bytes,5,opt,name=invitee_display_name" json:"invitee_display_name,omitempty"`
	Role               []uint32 `protobuf:"varint,6,rep,packed,name=role" json:"role,omitempty"`
	XXX_unrecognized   []byte   `json:"-"`
}

func (m *FriendInvitationParams) Reset()                    { *m = FriendInvitationParams{} }
func (m *FriendInvitationParams) String() string            { return proto.CompactTextString(m) }
func (*FriendInvitationParams) ProtoMessage()               {}
func (*FriendInvitationParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FriendInvitationParams) GetTargetEmail() string {
	if m != nil && m.TargetEmail != nil {
		return *m.TargetEmail
	}
	return ""
}

func (m *FriendInvitationParams) GetTargetBattleTag() string {
	if m != nil && m.TargetBattleTag != nil {
		return *m.TargetBattleTag
	}
	return ""
}

func (m *FriendInvitationParams) GetInviterBattleTag() string {
	if m != nil && m.InviterBattleTag != nil {
		return *m.InviterBattleTag
	}
	return ""
}

func (m *FriendInvitationParams) GetInviterFullName() string {
	if m != nil && m.InviterFullName != nil {
		return *m.InviterFullName
	}
	return ""
}

func (m *FriendInvitationParams) GetInviteeDisplayName() string {
	if m != nil && m.InviteeDisplayName != nil {
		return *m.InviteeDisplayName
	}
	return ""
}

func (m *FriendInvitationParams) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

var E_FriendInvitationParams_FriendParams = &proto.ExtensionDesc{
	ExtendedType:  (*invitation_types.InvitationParams)(nil),
	ExtensionType: (*FriendInvitationParams)(nil),
	Field:         103,
	Name:          "friends_types.FriendInvitationParams.friend_params",
	Tag:           "bytes,103,opt,name=friend_params",
}

func init() {
	proto.RegisterType((*Friend)(nil), "friends_types.Friend")
	proto.RegisterType((*FriendInvitation)(nil), "friends_types.FriendInvitation")
	proto.RegisterType((*FriendInvitationParams)(nil), "friends_types.FriendInvitationParams")
	proto.RegisterExtension(E_FriendInvitation_FriendInvite)
	proto.RegisterExtension(E_FriendInvitationParams_FriendParams)
}

var fileDescriptor0 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0xab, 0xd3, 0x40,
	0x14, 0x25, 0xe9, 0x87, 0xf6, 0x3e, 0x9f, 0xe4, 0x0d, 0x55, 0xc6, 0x52, 0xb1, 0x14, 0xc4, 0x6e,
	0x5e, 0x2a, 0xdd, 0xf9, 0x36, 0xa2, 0xe0, 0xc7, 0x5b, 0x08, 0x82, 0xee, 0xe3, 0xb4, 0xbd, 0x4d,
	0x06, 0x26, 0x1f, 0xcc, 0xdc, 0x16, 0xfa, 0x37, 0xdc, 0xf9, 0x53, 0xfc, 0x77, 0xa6, 0x33, 0xf9,
	0x68, 0x2b, 0x68, 0x57, 0x33, 0x39, 0xe7, 0xde, 0x93, 0x73, 0x4e, 0x02, 0x9f, 0x62, 0x49, 0xc9,
	0x76, 0x19, 0xae, 0xf2, 0x74, 0xfe, 0x19, 0x85, 0xa6, 0xe4, 0x9b, 0x4c, 0xe7, 0x89, 0xb9, 0x2d,
	0x74, 0x4e, 0xf9, 0x6d, 0x9c, 0xcf, 0x97, 0x19, 0xd2, 0x7c, 0xa3, 0x25, 0x66, 0x6b, 0x13, 0xd1,
	0xbe, 0x40, 0x73, 0xfa, 0x14, 0xda, 0x49, 0x76, 0x7d, 0x02, 0x8e, 0xde, 0x5e, 0xa6, 0x2b, 0x88,
	0xb4, 0x5c, 0x6e, 0x09, 0xdb, 0x9b, 0xd3, 0x1b, 0xbd, 0xb9, 0x4c, 0x00, 0x33, 0x92, 0xb4, 0xaf,
	0x8e, 0x6a, 0xf5, 0xcb, 0x65, 0xab, 0x32, 0xdb, 0x49, 0x12, 0x24, 0xf3, 0xac, 0x8a, 0x75, 0x0e,
	0x38, 0xb9, 0xe9, 0x6f, 0x0f, 0xfa, 0x1f, 0x6d, 0x38, 0x36, 0x06, 0x5f, 0xae, 0xb9, 0x37, 0xf1,
	0x67, 0x57, 0x8b, 0x20, 0xac, 0x5e, 0xfa, 0xc1, 0x1e, 0xf7, 0x6b, 0xf6, 0x0a, 0x06, 0x4d, 0x0a,
	0xee, 0x4f, 0x3a, 0xe5, 0xd0, 0x30, 0x6c, 0x73, 0xbd, 0xab, 0x6f, 0x2c, 0x80, 0xae, 0xce, 0x15,
	0xf2, 0x4e, 0x39, 0x73, 0xfd, 0xde, 0x0f, 0x3c, 0xf6, 0x04, 0xa0, 0xd0, 0x72, 0x27, 0x15, 0xc6,
	0x68, 0x78, 0x77, 0xe2, 0xcd, 0xba, 0x77, 0xde, 0x6b, 0xc6, 0x21, 0x68, 0xf6, 0x4d, 0x84, 0x45,
	0xbe, 0x4a, 0x78, 0xef, 0x40, 0xb2, 0x1b, 0x18, 0x6c, 0xb6, 0x4a, 0x45, 0x99, 0x48, 0x91, 0xf7,
	0x4b, 0x68, 0xc0, 0x18, 0xc0, 0xb2, 0x9c, 0x56, 0x18, 0x91, 0x88, 0xf9, 0x83, 0x03, 0x36, 0xfd,
	0xe5, 0x41, 0xe0, 0xbc, 0xdf, 0x37, 0xe1, 0xd8, 0x73, 0x78, 0xbc, 0x91, 0xda, 0x50, 0xa4, 0x71,
	0x85, 0x72, 0x87, 0x87, 0x44, 0xde, 0xec, 0xe1, 0x5d, 0x6f, 0x23, 0x94, 0x69, 0xdd, 0xf9, 0xb5,
	0xbb, 0xc5, 0x77, 0xa8, 0xbe, 0x6e, 0x64, 0x2b, 0x42, 0x36, 0x0e, 0xff, 0xea, 0xaa, 0xd5, 0xe7,
	0x71, 0xa9, 0x76, 0xb5, 0x78, 0x11, 0x9e, 0xfe, 0x26, 0xe7, 0x36, 0xa6, 0x3f, 0x7d, 0x78, 0x7a,
	0x0e, 0x7e, 0x15, 0x5a, 0xa4, 0x86, 0x0d, 0xe1, 0x11, 0x09, 0x1d, 0x23, 0x45, 0x98, 0x0a, 0xa9,
	0xac, 0xbf, 0x01, 0x7b, 0x06, 0x37, 0x15, 0x7a, 0x94, 0xd3, 0xb7, 0xd4, 0x08, 0x98, 0xb3, 0xa6,
	0x8f, 0xb9, 0x4e, 0xbd, 0x56, 0x73, 0x6d, 0x65, 0x5d, 0x4b, 0x8d, 0x61, 0xe8, 0x28, 0x8c, 0xd6,
	0xd2, 0x14, 0x4a, 0xec, 0x1d, 0xdb, 0xb3, 0x6c, 0x5d, 0x44, 0xbf, 0x29, 0xe2, 0x47, 0x53, 0x44,
	0xe1, 0x8c, 0x4e, 0xff, 0x55, 0x84, 0x0b, 0x53, 0xd5, 0xf1, 0xf2, 0x3f, 0x75, 0xb8, 0xe1, 0x3f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x53, 0xeb, 0x17, 0xc5, 0x90, 0x03, 0x00, 0x00,
}
