// Code generated by protoc-gen-go.
// source: github.com/HearthSim/hs-proto-go/bnet/presence_service/presence_service.proto
// DO NOT EDIT!

/*
Package presence_service is a generated protocol buffer package.

It is generated from these files:
	github.com/HearthSim/hs-proto-go/bnet/presence_service/presence_service.proto

It has these top-level messages:
	SubscribeRequest
	SubscribeNotificationRequest
	UnsubscribeRequest
	UpdateRequest
	QueryRequest
	QueryResponse
	OwnershipRequest
*/
package presence_service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import entity "github.com/HearthSim/hs-proto-go/bnet/entity"
import presence_types "github.com/HearthSim/hs-proto-go/bnet/presence_types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubscribeRequest struct {
	AgentId          *entity.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	EntityId         *entity.EntityId `protobuf:"bytes,2,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ObjectId         *uint64          `protobuf:"varint,3,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	ProgramId        []uint32         `protobuf:"fixed32,4,rep,name=program_id,json=programId" json:"program_id,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SubscribeRequest) Reset()                    { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()               {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubscribeRequest) GetAgentId() *entity.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SubscribeRequest) GetEntityId() *entity.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *SubscribeRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *SubscribeRequest) GetProgramId() []uint32 {
	if m != nil {
		return m.ProgramId
	}
	return nil
}

type SubscribeNotificationRequest struct {
	EntityId         *entity.EntityId `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SubscribeNotificationRequest) Reset()                    { *m = SubscribeNotificationRequest{} }
func (m *SubscribeNotificationRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeNotificationRequest) ProtoMessage()               {}
func (*SubscribeNotificationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubscribeNotificationRequest) GetEntityId() *entity.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

type UnsubscribeRequest struct {
	AgentId          *entity.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	EntityId         *entity.EntityId `protobuf:"bytes,2,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *UnsubscribeRequest) Reset()                    { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()               {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UnsubscribeRequest) GetAgentId() *entity.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnsubscribeRequest) GetEntityId() *entity.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

type UpdateRequest struct {
	EntityId         *entity.EntityId                 `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	FieldOperation   []*presence_types.FieldOperation `protobuf:"bytes,2,rep,name=field_operation,json=fieldOperation" json:"field_operation,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UpdateRequest) GetEntityId() *entity.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *UpdateRequest) GetFieldOperation() []*presence_types.FieldOperation {
	if m != nil {
		return m.FieldOperation
	}
	return nil
}

type QueryRequest struct {
	EntityId         *entity.EntityId           `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	Key              []*presence_types.FieldKey `protobuf:"bytes,2,rep,name=key" json:"key,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *QueryRequest) Reset()                    { *m = QueryRequest{} }
func (m *QueryRequest) String() string            { return proto.CompactTextString(m) }
func (*QueryRequest) ProtoMessage()               {}
func (*QueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *QueryRequest) GetEntityId() *entity.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *QueryRequest) GetKey() []*presence_types.FieldKey {
	if m != nil {
		return m.Key
	}
	return nil
}

type QueryResponse struct {
	Field            []*presence_types.Field `protobuf:"bytes,2,rep,name=field" json:"field,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *QueryResponse) Reset()                    { *m = QueryResponse{} }
func (m *QueryResponse) String() string            { return proto.CompactTextString(m) }
func (*QueryResponse) ProtoMessage()               {}
func (*QueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *QueryResponse) GetField() []*presence_types.Field {
	if m != nil {
		return m.Field
	}
	return nil
}

type OwnershipRequest struct {
	EntityId         *entity.EntityId `protobuf:"bytes,1,req,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	ReleaseOwnership *bool            `protobuf:"varint,2,opt,name=release_ownership,json=releaseOwnership,def=0" json:"release_ownership,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *OwnershipRequest) Reset()                    { *m = OwnershipRequest{} }
func (m *OwnershipRequest) String() string            { return proto.CompactTextString(m) }
func (*OwnershipRequest) ProtoMessage()               {}
func (*OwnershipRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_OwnershipRequest_ReleaseOwnership bool = false

func (m *OwnershipRequest) GetEntityId() *entity.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func (m *OwnershipRequest) GetReleaseOwnership() bool {
	if m != nil && m.ReleaseOwnership != nil {
		return *m.ReleaseOwnership
	}
	return Default_OwnershipRequest_ReleaseOwnership
}

func init() {
	proto.RegisterType((*SubscribeRequest)(nil), "presence_service.SubscribeRequest")
	proto.RegisterType((*SubscribeNotificationRequest)(nil), "presence_service.SubscribeNotificationRequest")
	proto.RegisterType((*UnsubscribeRequest)(nil), "presence_service.UnsubscribeRequest")
	proto.RegisterType((*UpdateRequest)(nil), "presence_service.UpdateRequest")
	proto.RegisterType((*QueryRequest)(nil), "presence_service.QueryRequest")
	proto.RegisterType((*QueryResponse)(nil), "presence_service.QueryResponse")
	proto.RegisterType((*OwnershipRequest)(nil), "presence_service.OwnershipRequest")
}

func init() {
	proto.RegisterFile("github.com/HearthSim/hs-proto-go/bnet/presence_service/presence_service.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 411 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x93, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0x95, 0x74, 0xd3, 0xda, 0x33, 0xc6, 0x32, 0x4b, 0x48, 0xd5, 0xf8, 0x50, 0x94, 0xab,
	0x88, 0xa9, 0x8d, 0x94, 0x3b, 0x10, 0xb7, 0x7c, 0x44, 0x68, 0x0c, 0x5c, 0xed, 0x3a, 0xca, 0xc7,
	0x49, 0x62, 0x68, 0x6d, 0x63, 0x3b, 0xa0, 0x3c, 0x01, 0xef, 0xc2, 0x53, 0xa2, 0x24, 0xee, 0xa4,
	0x95, 0x4a, 0x40, 0x2f, 0xb8, 0x72, 0x7c, 0xce, 0xcf, 0xe7, 0xff, 0xb3, 0x22, 0xc3, 0x75, 0xcd,
	0x4c, 0xd3, 0xe6, 0xcb, 0x42, 0x6c, 0xa2, 0x77, 0x98, 0x29, 0xd3, 0xac, 0xd8, 0x26, 0x6a, 0xf4,
	0x42, 0x2a, 0x61, 0xc4, 0xa2, 0x16, 0x51, 0xce, 0xd1, 0x44, 0x52, 0xa1, 0x46, 0x5e, 0x60, 0xaa,
	0x51, 0x7d, 0x63, 0x05, 0xfe, 0x56, 0x58, 0x0e, 0x3c, 0xf1, 0x76, 0xeb, 0x97, 0x2f, 0xfe, 0x2e,
	0x00, 0xb9, 0x61, 0xa6, 0xb3, 0xcb, 0x38, 0xec, 0x32, 0xf9, 0x47, 0x37, 0xd3, 0x49, 0xd4, 0x3b,
	0xdb, 0x71, 0x54, 0xf0, 0xd3, 0x01, 0x6f, 0xd5, 0xe6, 0xba, 0x50, 0x2c, 0x47, 0x8a, 0x5f, 0x5b,
	0xd4, 0x86, 0x5c, 0xc1, 0x34, 0xab, 0x91, 0x9b, 0x94, 0x95, 0x73, 0xc7, 0x77, 0xc2, 0xd3, 0xd8,
	0x5b, 0x5a, 0x81, 0xd7, 0xc3, 0x92, 0x94, 0xf4, 0x64, 0x20, 0x92, 0x92, 0x2c, 0x60, 0x36, 0xf6,
	0x7a, 0xda, 0xf5, 0xdd, 0xbd, 0xf4, 0x14, 0xed, 0x17, 0x79, 0x0c, 0x33, 0x91, 0x7f, 0xc6, 0x62,
	0x18, 0x3e, 0xf1, 0xdd, 0xf0, 0x88, 0x4e, 0xc7, 0x42, 0x52, 0x92, 0xa7, 0x00, 0x52, 0x89, 0x5a,
	0x65, 0x9b, 0xbe, 0x7b, 0xe4, 0x4f, 0xc2, 0x13, 0x3a, 0xb3, 0x95, 0xa4, 0x0c, 0xae, 0xe1, 0xc9,
	0x9d, 0xeb, 0x07, 0x61, 0x58, 0xc5, 0x8a, 0xcc, 0x30, 0xc1, 0xb7, 0xde, 0xf7, 0x54, 0x9c, 0x3f,
	0xa9, 0x04, 0x12, 0xc8, 0x2d, 0xd7, 0xff, 0xf1, 0xf2, 0xc1, 0x0f, 0x07, 0xce, 0x6e, 0x65, 0x99,
	0x19, 0x3c, 0x4c, 0x99, 0xbc, 0x85, 0xf3, 0x8a, 0xe1, 0xba, 0x4c, 0x85, 0x44, 0x35, 0xdc, 0x7d,
	0xee, 0xfa, 0x93, 0xf0, 0x34, 0x7e, 0xb6, 0xdc, 0xf9, 0xbd, 0x6f, 0x7a, 0xec, 0x66, 0x4b, 0xd1,
	0x87, 0xd5, 0xbd, 0x7d, 0xc0, 0xe0, 0xc1, 0xa7, 0x16, 0x55, 0x77, 0xa0, 0xc7, 0x73, 0x98, 0x7c,
	0xc1, 0xce, 0x66, 0xcf, 0xf7, 0x66, 0xbf, 0xc7, 0x8e, 0xf6, 0x50, 0xf0, 0x0a, 0xce, 0x6c, 0x94,
	0x96, 0x82, 0x6b, 0x24, 0x57, 0x70, 0x3c, 0xd8, 0xd8, 0xe3, 0x8f, 0xf6, 0x1e, 0xa7, 0x23, 0x13,
	0xb4, 0xe0, 0xdd, 0x7c, 0xe7, 0xa8, 0x74, 0xc3, 0xe4, 0x81, 0xb2, 0x31, 0x5c, 0x28, 0x5c, 0x63,
	0xa6, 0x31, 0x15, 0xdb, 0x51, 0x73, 0xd7, 0x77, 0xc2, 0xe9, 0xcb, 0xe3, 0x2a, 0x5b, 0x6b, 0xa4,
	0x9e, 0xed, 0xdf, 0x25, 0xc5, 0x17, 0x70, 0xfe, 0xd1, 0x5a, 0xad, 0xc6, 0x07, 0xfb, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x1b, 0x92, 0x97, 0xb7, 0x12, 0x04, 0x00, 0x00,
}
