// Code generated by protoc-gen-go.
// source: bnet/protocol/notification/notification.proto
// DO NOT EDIT!

package bnet_protocol_notification

import proto "github.com/golang/protobuf/proto"
import json "encoding/json"
import math "math"
import bnet_protocol "github.com/HearthSim/hs-proto-go/bnet/protocol"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// ref: bnet.protocol.notification.FindClientRequest
type FindClientRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,req,name=entity_id" json:"entity_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *FindClientRequest) Reset()         { *m = FindClientRequest{} }
func (m *FindClientRequest) String() string { return proto.CompactTextString(m) }
func (*FindClientRequest) ProtoMessage()    {}

func (m *FindClientRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

// ref: bnet.protocol.notification.FindClientResponse
type FindClientResponse struct {
	Label            *uint32                  `protobuf:"varint,1,req,name=label" json:"label,omitempty"`
	ClientProcessId  *bnet_protocol.ProcessId `protobuf:"bytes,2,opt,name=client_process_id" json:"client_process_id,omitempty"`
	XXX_unrecognized []byte                   `json:"-"`
}

func (m *FindClientResponse) Reset()         { *m = FindClientResponse{} }
func (m *FindClientResponse) String() string { return proto.CompactTextString(m) }
func (*FindClientResponse) ProtoMessage()    {}

func (m *FindClientResponse) GetLabel() uint32 {
	if m != nil && m.Label != nil {
		return *m.Label
	}
	return 0
}

func (m *FindClientResponse) GetClientProcessId() *bnet_protocol.ProcessId {
	if m != nil {
		return m.ClientProcessId
	}
	return nil
}

// ref: bnet.protocol.notification.Notification
type Notification struct {
	SenderId         *bnet_protocol.EntityId    `protobuf:"bytes,1,opt,name=sender_id" json:"sender_id,omitempty"`
	TargetId         *bnet_protocol.EntityId    `protobuf:"bytes,2,req,name=target_id" json:"target_id,omitempty"`
	Type             *string                    `protobuf:"bytes,3,req,name=type" json:"type,omitempty"`
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,4,rep,name=attribute" json:"attribute,omitempty"`
	SenderAccountId  *bnet_protocol.EntityId    `protobuf:"bytes,5,opt,name=sender_account_id" json:"sender_account_id,omitempty"`
	TargetAccountId  *bnet_protocol.EntityId    `protobuf:"bytes,6,opt,name=target_account_id" json:"target_account_id,omitempty"`
	SenderBattleTag  *string                    `protobuf:"bytes,7,opt,name=sender_battle_tag" json:"sender_battle_tag,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}

func (m *Notification) GetSenderId() *bnet_protocol.EntityId {
	if m != nil {
		return m.SenderId
	}
	return nil
}

func (m *Notification) GetTargetId() *bnet_protocol.EntityId {
	if m != nil {
		return m.TargetId
	}
	return nil
}

func (m *Notification) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *Notification) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Notification) GetSenderAccountId() *bnet_protocol.EntityId {
	if m != nil {
		return m.SenderAccountId
	}
	return nil
}

func (m *Notification) GetTargetAccountId() *bnet_protocol.EntityId {
	if m != nil {
		return m.TargetAccountId
	}
	return nil
}

func (m *Notification) GetSenderBattleTag() string {
	if m != nil && m.SenderBattleTag != nil {
		return *m.SenderBattleTag
	}
	return ""
}

// ref: bnet.protocol.notification.RegisterClientRequest
type RegisterClientRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,req,name=entity_id" json:"entity_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RegisterClientRequest) Reset()         { *m = RegisterClientRequest{} }
func (m *RegisterClientRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterClientRequest) ProtoMessage()    {}

func (m *RegisterClientRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

// ref: bnet.protocol.notification.UnregisterClientRequest
type UnregisterClientRequest struct {
	EntityId         *bnet_protocol.EntityId `protobuf:"bytes,1,req,name=entity_id" json:"entity_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UnregisterClientRequest) Reset()         { *m = UnregisterClientRequest{} }
func (m *UnregisterClientRequest) String() string { return proto.CompactTextString(m) }
func (*UnregisterClientRequest) ProtoMessage()    {}

func (m *UnregisterClientRequest) GetEntityId() *bnet_protocol.EntityId {
	if m != nil {
		return m.EntityId
	}
	return nil
}

func init() {
}
