// Code generated by protoc-gen-go.
// source: github.com/HearthSim/hs-proto-go/bnet/authentication_service/authentication_service.proto
// DO NOT EDIT!

/*
Package authentication_service is a generated protocol buffer package.

It is generated from these files:
	github.com/HearthSim/hs-proto-go/bnet/authentication_service/authentication_service.proto

It has these top-level messages:
	ModuleLoadRequest
	ModuleNotification
	ModuleMessageRequest
	LogonRequest
	LogonResult
	GenerateSSOTokenRequest
	GenerateSSOTokenResponse
	LogonUpdateRequest
	LogonQueueUpdateRequest
	AccountSettingsNotification
	ServerStateChangeRequest
	VersionInfo
	VersionInfoNotification
	MemModuleLoadRequest
	MemModuleLoadResponse
	SelectGameAccountRequest
	GameAccountSelectedRequest
	VerifyWebCredentialsRequest
*/
package authentication_service

import proto "github.com/golang/protobuf/proto"
import math "math"
import account_types "github.com/HearthSim/hs-proto-go/bnet/account_types"
import content_handle "github.com/HearthSim/hs-proto-go/bnet/content_handle"
import entity "github.com/HearthSim/hs-proto-go/bnet/entity"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ModuleLoadRequest struct {
	ModuleHandle     *content_handle.ContentHandle `protobuf:"bytes,1,req,name=module_handle" json:"module_handle,omitempty"`
	Message          []byte                        `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *ModuleLoadRequest) Reset()         { *m = ModuleLoadRequest{} }
func (m *ModuleLoadRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleLoadRequest) ProtoMessage()    {}

func (m *ModuleLoadRequest) GetModuleHandle() *content_handle.ContentHandle {
	if m != nil {
		return m.ModuleHandle
	}
	return nil
}

func (m *ModuleLoadRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type ModuleNotification struct {
	ModuleId         *int32  `protobuf:"varint,2,opt,name=module_id" json:"module_id,omitempty"`
	Result           *uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ModuleNotification) Reset()         { *m = ModuleNotification{} }
func (m *ModuleNotification) String() string { return proto.CompactTextString(m) }
func (*ModuleNotification) ProtoMessage()    {}

func (m *ModuleNotification) GetModuleId() int32 {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return 0
}

func (m *ModuleNotification) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

type ModuleMessageRequest struct {
	ModuleId         *int32 `protobuf:"varint,1,req,name=module_id" json:"module_id,omitempty"`
	Message          []byte `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ModuleMessageRequest) Reset()         { *m = ModuleMessageRequest{} }
func (m *ModuleMessageRequest) String() string { return proto.CompactTextString(m) }
func (*ModuleMessageRequest) ProtoMessage()    {}

func (m *ModuleMessageRequest) GetModuleId() int32 {
	if m != nil && m.ModuleId != nil {
		return *m.ModuleId
	}
	return 0
}

func (m *ModuleMessageRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

type LogonRequest struct {
	Program                      *string `protobuf:"bytes,1,opt,name=program" json:"program,omitempty"`
	Platform                     *string `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Locale                       *string `protobuf:"bytes,3,opt,name=locale" json:"locale,omitempty"`
	Email                        *string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Version                      *string `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	ApplicationVersion           *int32  `protobuf:"varint,6,opt,name=application_version" json:"application_version,omitempty"`
	PublicComputer               *bool   `protobuf:"varint,7,opt,name=public_computer" json:"public_computer,omitempty"`
	SsoId                        []byte  `protobuf:"bytes,8,opt,name=sso_id" json:"sso_id,omitempty"`
	DisconnectOnCookieFail       *bool   `protobuf:"varint,9,opt,name=disconnect_on_cookie_fail,def=0" json:"disconnect_on_cookie_fail,omitempty"`
	AllowLogonQueueNotifications *bool   `protobuf:"varint,10,opt,name=allow_logon_queue_notifications,def=0" json:"allow_logon_queue_notifications,omitempty"`
	WebClientVerification        *bool   `protobuf:"varint,11,opt,name=web_client_verification,def=0" json:"web_client_verification,omitempty"`
	CachedWebCredentials         []byte  `protobuf:"bytes,12,opt,name=cached_web_credentials" json:"cached_web_credentials,omitempty"`
	UserAgent                    *string `protobuf:"bytes,14,opt,name=user_agent" json:"user_agent,omitempty"`
	XXX_unrecognized             []byte  `json:"-"`
}

func (m *LogonRequest) Reset()         { *m = LogonRequest{} }
func (m *LogonRequest) String() string { return proto.CompactTextString(m) }
func (*LogonRequest) ProtoMessage()    {}

const Default_LogonRequest_DisconnectOnCookieFail bool = false
const Default_LogonRequest_AllowLogonQueueNotifications bool = false
const Default_LogonRequest_WebClientVerification bool = false

func (m *LogonRequest) GetProgram() string {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return ""
}

func (m *LogonRequest) GetPlatform() string {
	if m != nil && m.Platform != nil {
		return *m.Platform
	}
	return ""
}

func (m *LogonRequest) GetLocale() string {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return ""
}

func (m *LogonRequest) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *LogonRequest) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return ""
}

func (m *LogonRequest) GetApplicationVersion() int32 {
	if m != nil && m.ApplicationVersion != nil {
		return *m.ApplicationVersion
	}
	return 0
}

func (m *LogonRequest) GetPublicComputer() bool {
	if m != nil && m.PublicComputer != nil {
		return *m.PublicComputer
	}
	return false
}

func (m *LogonRequest) GetSsoId() []byte {
	if m != nil {
		return m.SsoId
	}
	return nil
}

func (m *LogonRequest) GetDisconnectOnCookieFail() bool {
	if m != nil && m.DisconnectOnCookieFail != nil {
		return *m.DisconnectOnCookieFail
	}
	return Default_LogonRequest_DisconnectOnCookieFail
}

func (m *LogonRequest) GetAllowLogonQueueNotifications() bool {
	if m != nil && m.AllowLogonQueueNotifications != nil {
		return *m.AllowLogonQueueNotifications
	}
	return Default_LogonRequest_AllowLogonQueueNotifications
}

func (m *LogonRequest) GetWebClientVerification() bool {
	if m != nil && m.WebClientVerification != nil {
		return *m.WebClientVerification
	}
	return Default_LogonRequest_WebClientVerification
}

func (m *LogonRequest) GetCachedWebCredentials() []byte {
	if m != nil {
		return m.CachedWebCredentials
	}
	return nil
}

func (m *LogonRequest) GetUserAgent() string {
	if m != nil && m.UserAgent != nil {
		return *m.UserAgent
	}
	return ""
}

type LogonResult struct {
	ErrorCode        *uint32            `protobuf:"varint,1,req,name=error_code" json:"error_code,omitempty"`
	Account          *entity.EntityId   `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	GameAccount      []*entity.EntityId `protobuf:"bytes,3,rep,name=game_account" json:"game_account,omitempty"`
	Email            *string            `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	AvailableRegion  []uint32           `protobuf:"varint,5,rep,name=available_region" json:"available_region,omitempty"`
	ConnectedRegion  *uint32            `protobuf:"varint,6,opt,name=connected_region" json:"connected_region,omitempty"`
	BattleTag        *string            `protobuf:"bytes,7,opt,name=battle_tag" json:"battle_tag,omitempty"`
	GeoipCountry     *string            `protobuf:"bytes,8,opt,name=geoip_country" json:"geoip_country,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *LogonResult) Reset()         { *m = LogonResult{} }
func (m *LogonResult) String() string { return proto.CompactTextString(m) }
func (*LogonResult) ProtoMessage()    {}

func (m *LogonResult) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *LogonResult) GetAccount() *entity.EntityId {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *LogonResult) GetGameAccount() []*entity.EntityId {
	if m != nil {
		return m.GameAccount
	}
	return nil
}

func (m *LogonResult) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func (m *LogonResult) GetAvailableRegion() []uint32 {
	if m != nil {
		return m.AvailableRegion
	}
	return nil
}

func (m *LogonResult) GetConnectedRegion() uint32 {
	if m != nil && m.ConnectedRegion != nil {
		return *m.ConnectedRegion
	}
	return 0
}

func (m *LogonResult) GetBattleTag() string {
	if m != nil && m.BattleTag != nil {
		return *m.BattleTag
	}
	return ""
}

func (m *LogonResult) GetGeoipCountry() string {
	if m != nil && m.GeoipCountry != nil {
		return *m.GeoipCountry
	}
	return ""
}

type GenerateSSOTokenRequest struct {
	Program          *uint32 `protobuf:"fixed32,1,opt,name=program" json:"program,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GenerateSSOTokenRequest) Reset()         { *m = GenerateSSOTokenRequest{} }
func (m *GenerateSSOTokenRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateSSOTokenRequest) ProtoMessage()    {}

func (m *GenerateSSOTokenRequest) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

type GenerateSSOTokenResponse struct {
	SsoId            []byte `protobuf:"bytes,1,opt,name=sso_id" json:"sso_id,omitempty"`
	SsoSecret        []byte `protobuf:"bytes,2,opt,name=sso_secret" json:"sso_secret,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GenerateSSOTokenResponse) Reset()         { *m = GenerateSSOTokenResponse{} }
func (m *GenerateSSOTokenResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateSSOTokenResponse) ProtoMessage()    {}

func (m *GenerateSSOTokenResponse) GetSsoId() []byte {
	if m != nil {
		return m.SsoId
	}
	return nil
}

func (m *GenerateSSOTokenResponse) GetSsoSecret() []byte {
	if m != nil {
		return m.SsoSecret
	}
	return nil
}

type LogonUpdateRequest struct {
	ErrorCode        *uint32 `protobuf:"varint,1,req,name=error_code" json:"error_code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogonUpdateRequest) Reset()         { *m = LogonUpdateRequest{} }
func (m *LogonUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*LogonUpdateRequest) ProtoMessage()    {}

func (m *LogonUpdateRequest) GetErrorCode() uint32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

type LogonQueueUpdateRequest struct {
	Position          *uint32 `protobuf:"varint,1,req,name=position" json:"position,omitempty"`
	EstimatedTime     *uint64 `protobuf:"varint,2,req,name=estimated_time" json:"estimated_time,omitempty"`
	EtaDeviationInSec *uint64 `protobuf:"varint,3,req,name=eta_deviation_in_sec" json:"eta_deviation_in_sec,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (m *LogonQueueUpdateRequest) Reset()         { *m = LogonQueueUpdateRequest{} }
func (m *LogonQueueUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*LogonQueueUpdateRequest) ProtoMessage()    {}

func (m *LogonQueueUpdateRequest) GetPosition() uint32 {
	if m != nil && m.Position != nil {
		return *m.Position
	}
	return 0
}

func (m *LogonQueueUpdateRequest) GetEstimatedTime() uint64 {
	if m != nil && m.EstimatedTime != nil {
		return *m.EstimatedTime
	}
	return 0
}

func (m *LogonQueueUpdateRequest) GetEtaDeviationInSec() uint64 {
	if m != nil && m.EtaDeviationInSec != nil {
		return *m.EtaDeviationInSec
	}
	return 0
}

type AccountSettingsNotification struct {
	Licenses         []*account_types.AccountLicense `protobuf:"bytes,1,rep,name=licenses" json:"licenses,omitempty"`
	IsUsingRid       *bool                           `protobuf:"varint,2,opt,name=is_using_rid" json:"is_using_rid,omitempty"`
	IsPlayingFromIgr *bool                           `protobuf:"varint,3,opt,name=is_playing_from_igr" json:"is_playing_from_igr,omitempty"`
	CanReceiveVoice  *bool                           `protobuf:"varint,4,opt,name=can_receive_voice" json:"can_receive_voice,omitempty"`
	CanSendVoice     *bool                           `protobuf:"varint,5,opt,name=can_send_voice" json:"can_send_voice,omitempty"`
	XXX_unrecognized []byte                          `json:"-"`
}

func (m *AccountSettingsNotification) Reset()         { *m = AccountSettingsNotification{} }
func (m *AccountSettingsNotification) String() string { return proto.CompactTextString(m) }
func (*AccountSettingsNotification) ProtoMessage()    {}

func (m *AccountSettingsNotification) GetLicenses() []*account_types.AccountLicense {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func (m *AccountSettingsNotification) GetIsUsingRid() bool {
	if m != nil && m.IsUsingRid != nil {
		return *m.IsUsingRid
	}
	return false
}

func (m *AccountSettingsNotification) GetIsPlayingFromIgr() bool {
	if m != nil && m.IsPlayingFromIgr != nil {
		return *m.IsPlayingFromIgr
	}
	return false
}

func (m *AccountSettingsNotification) GetCanReceiveVoice() bool {
	if m != nil && m.CanReceiveVoice != nil {
		return *m.CanReceiveVoice
	}
	return false
}

func (m *AccountSettingsNotification) GetCanSendVoice() bool {
	if m != nil && m.CanSendVoice != nil {
		return *m.CanSendVoice
	}
	return false
}

type ServerStateChangeRequest struct {
	State            *uint32 `protobuf:"varint,1,req,name=state" json:"state,omitempty"`
	EventTime        *uint64 `protobuf:"varint,2,req,name=event_time" json:"event_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ServerStateChangeRequest) Reset()         { *m = ServerStateChangeRequest{} }
func (m *ServerStateChangeRequest) String() string { return proto.CompactTextString(m) }
func (*ServerStateChangeRequest) ProtoMessage()    {}

func (m *ServerStateChangeRequest) GetState() uint32 {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *ServerStateChangeRequest) GetEventTime() uint64 {
	if m != nil && m.EventTime != nil {
		return *m.EventTime
	}
	return 0
}

type VersionInfo struct {
	Number           *uint32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Patch            *string `protobuf:"bytes,2,opt,name=patch" json:"patch,omitempty"`
	IsOptional       *bool   `protobuf:"varint,3,opt,name=is_optional" json:"is_optional,omitempty"`
	KickTime         *uint64 `protobuf:"varint,4,opt,name=kick_time" json:"kick_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *VersionInfo) Reset()         { *m = VersionInfo{} }
func (m *VersionInfo) String() string { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()    {}

func (m *VersionInfo) GetNumber() uint32 {
	if m != nil && m.Number != nil {
		return *m.Number
	}
	return 0
}

func (m *VersionInfo) GetPatch() string {
	if m != nil && m.Patch != nil {
		return *m.Patch
	}
	return ""
}

func (m *VersionInfo) GetIsOptional() bool {
	if m != nil && m.IsOptional != nil {
		return *m.IsOptional
	}
	return false
}

func (m *VersionInfo) GetKickTime() uint64 {
	if m != nil && m.KickTime != nil {
		return *m.KickTime
	}
	return 0
}

type VersionInfoNotification struct {
	VersionInfo      *VersionInfo `protobuf:"bytes,1,opt,name=version_info" json:"version_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *VersionInfoNotification) Reset()         { *m = VersionInfoNotification{} }
func (m *VersionInfoNotification) String() string { return proto.CompactTextString(m) }
func (*VersionInfoNotification) ProtoMessage()    {}

func (m *VersionInfoNotification) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

type MemModuleLoadRequest struct {
	Handle           *content_handle.ContentHandle `protobuf:"bytes,1,req,name=handle" json:"handle,omitempty"`
	Key              []byte                        `protobuf:"bytes,2,req,name=key" json:"key,omitempty"`
	Input            []byte                        `protobuf:"bytes,3,req,name=input" json:"input,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (m *MemModuleLoadRequest) Reset()         { *m = MemModuleLoadRequest{} }
func (m *MemModuleLoadRequest) String() string { return proto.CompactTextString(m) }
func (*MemModuleLoadRequest) ProtoMessage()    {}

func (m *MemModuleLoadRequest) GetHandle() *content_handle.ContentHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *MemModuleLoadRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MemModuleLoadRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

type MemModuleLoadResponse struct {
	Data             []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MemModuleLoadResponse) Reset()         { *m = MemModuleLoadResponse{} }
func (m *MemModuleLoadResponse) String() string { return proto.CompactTextString(m) }
func (*MemModuleLoadResponse) ProtoMessage()    {}

func (m *MemModuleLoadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SelectGameAccountRequest struct {
	GameAccount      *entity.EntityId `protobuf:"bytes,1,req,name=game_account" json:"game_account,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *SelectGameAccountRequest) Reset()         { *m = SelectGameAccountRequest{} }
func (m *SelectGameAccountRequest) String() string { return proto.CompactTextString(m) }
func (*SelectGameAccountRequest) ProtoMessage()    {}

func (m *SelectGameAccountRequest) GetGameAccount() *entity.EntityId {
	if m != nil {
		return m.GameAccount
	}
	return nil
}

type GameAccountSelectedRequest struct {
	Result           *uint32          `protobuf:"varint,1,req,name=result" json:"result,omitempty"`
	GameAccount      *entity.EntityId `protobuf:"bytes,2,opt,name=game_account" json:"game_account,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *GameAccountSelectedRequest) Reset()         { *m = GameAccountSelectedRequest{} }
func (m *GameAccountSelectedRequest) String() string { return proto.CompactTextString(m) }
func (*GameAccountSelectedRequest) ProtoMessage()    {}

func (m *GameAccountSelectedRequest) GetResult() uint32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *GameAccountSelectedRequest) GetGameAccount() *entity.EntityId {
	if m != nil {
		return m.GameAccount
	}
	return nil
}

type VerifyWebCredentialsRequest struct {
	WebCredentials   []byte `protobuf:"bytes,1,opt,name=web_credentials" json:"web_credentials,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *VerifyWebCredentialsRequest) Reset()         { *m = VerifyWebCredentialsRequest{} }
func (m *VerifyWebCredentialsRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyWebCredentialsRequest) ProtoMessage()    {}

func (m *VerifyWebCredentialsRequest) GetWebCredentials() []byte {
	if m != nil {
		return m.WebCredentials
	}
	return nil
}
