// Code generated by protoc-gen-go.
// source: github.com/HearthSim/hs-proto-go/bnet/content_handle/content_handle.proto
// DO NOT EDIT!

/*
Package content_handle is a generated protocol buffer package.

It is generated from these files:
	github.com/HearthSim/hs-proto-go/bnet/content_handle/content_handle.proto

It has these top-level messages:
	ContentHandle
	Path
*/
package content_handle

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ContentHandle struct {
	Region           *uint32 `protobuf:"fixed32,1,req,name=region" json:"region,omitempty"`
	Usage            *uint32 `protobuf:"fixed32,2,req,name=usage" json:"usage,omitempty"`
	Hash             []byte  `protobuf:"bytes,3,req,name=hash" json:"hash,omitempty"`
	ProtoUrl         *string `protobuf:"bytes,4,opt,name=proto_url,json=protoUrl" json:"proto_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ContentHandle) Reset()                    { *m = ContentHandle{} }
func (m *ContentHandle) String() string            { return proto.CompactTextString(m) }
func (*ContentHandle) ProtoMessage()               {}
func (*ContentHandle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ContentHandle) GetRegion() uint32 {
	if m != nil && m.Region != nil {
		return *m.Region
	}
	return 0
}

func (m *ContentHandle) GetUsage() uint32 {
	if m != nil && m.Usage != nil {
		return *m.Usage
	}
	return 0
}

func (m *ContentHandle) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ContentHandle) GetProtoUrl() string {
	if m != nil && m.ProtoUrl != nil {
		return *m.ProtoUrl
	}
	return ""
}

type Path struct {
	Ordinal          []uint32 `protobuf:"varint,1,rep,packed,name=ordinal" json:"ordinal,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Path) GetOrdinal() []uint32 {
	if m != nil {
		return m.Ordinal
	}
	return nil
}

func init() {
	proto.RegisterType((*ContentHandle)(nil), "content_handle.ContentHandle")
	proto.RegisterType((*Path)(nil), "content_handle.Path")
}

func init() {
	proto.RegisterFile("github.com/HearthSim/hs-proto-go/bnet/content_handle/content_handle.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0xcd, 0xc1, 0x4b, 0xc6, 0x20,
	0x18, 0xc7, 0x71, 0xf4, 0x5d, 0xbd, 0xed, 0xa1, 0x45, 0x48, 0x84, 0x50, 0x07, 0x19, 0x1d, 0xbc,
	0x6c, 0xfe, 0x0f, 0x75, 0x59, 0xb7, 0x30, 0x3a, 0x0f, 0xb7, 0x89, 0x0a, 0x4e, 0xc3, 0xb9, 0xff,
	0x3f, 0x70, 0x75, 0xe8, 0xbd, 0x3d, 0xdf, 0x0f, 0x0f, 0xfc, 0xe0, 0xdd, 0xb8, 0x6c, 0xf7, 0xa9,
	0x9f, 0xe3, 0x2a, 0x06, 0xad, 0x52, 0xb6, 0x9f, 0x6e, 0x15, 0x76, 0xeb, 0xbe, 0x53, 0xcc, 0xb1,
	0x33, 0x51, 0x4c, 0x41, 0x67, 0x31, 0xc7, 0x90, 0x75, 0xc8, 0xa3, 0x55, 0x61, 0xf1, 0xfa, 0x22,
	0xfb, 0xf2, 0x4b, 0xee, 0xfe, 0x6b, 0x1b, 0xa0, 0x79, 0x3b, 0x64, 0x28, 0x40, 0x1e, 0xe1, 0x3a,
	0x69, 0xe3, 0x62, 0xa0, 0x88, 0x61, 0x7e, 0x96, 0xbf, 0x45, 0x1e, 0xe0, 0x6a, 0xdf, 0x94, 0xd1,
	0x14, 0x17, 0x3e, 0x82, 0x10, 0xa8, 0xac, 0xda, 0x2c, 0x3d, 0x31, 0xcc, 0x6f, 0x65, 0xb9, 0xc9,
	0x13, 0xd4, 0x65, 0x6b, 0xdc, 0x93, 0xa7, 0x15, 0x43, 0xbc, 0x96, 0x37, 0x05, 0xbe, 0x92, 0x6f,
	0x5f, 0xa0, 0xfa, 0x50, 0xd9, 0x92, 0x67, 0x38, 0xc7, 0xb4, 0xb8, 0xa0, 0x3c, 0x45, 0xec, 0xc4,
	0x9b, 0x57, 0x7c, 0x8f, 0xe4, 0x1f, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xce, 0x70, 0xe7, 0xc8,
	0xf1, 0x00, 0x00, 0x00,
}
