// Code generated by protoc-gen-go.
// source: github.com/HearthSim/hs-proto-go/bnet/channel_types/channel_types.proto
// DO NOT EDIT!

/*
Package channel_types is a generated protocol buffer package.

It is generated from these files:
	github.com/HearthSim/hs-proto-go/bnet/channel_types/channel_types.proto

It has these top-level messages:
	Message
	FindChannelOptions
	ChannelDescription
	ChannelInfo
	ChannelState
	MemberState
	Member
*/
package channel_types

import proto "github.com/golang/protobuf/proto"
import math "math"
import attribute "github.com/HearthSim/hs-proto-go/bnet/attribute"
import entity "github.com/HearthSim/hs-proto-go/bnet/entity"
import invitation_types "github.com/HearthSim/hs-proto-go/bnet/invitation_types"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type ChannelState_PrivacyLevel int32

const (
	ChannelState_PRIVACY_LEVEL_OPEN                       ChannelState_PrivacyLevel = 1
	ChannelState_PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND ChannelState_PrivacyLevel = 2
	ChannelState_PRIVACY_LEVEL_OPEN_INVITATION            ChannelState_PrivacyLevel = 3
	ChannelState_PRIVACY_LEVEL_CLOSED                     ChannelState_PrivacyLevel = 4
)

var ChannelState_PrivacyLevel_name = map[int32]string{
	1: "PRIVACY_LEVEL_OPEN",
	2: "PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND",
	3: "PRIVACY_LEVEL_OPEN_INVITATION",
	4: "PRIVACY_LEVEL_CLOSED",
}
var ChannelState_PrivacyLevel_value = map[string]int32{
	"PRIVACY_LEVEL_OPEN":                       1,
	"PRIVACY_LEVEL_OPEN_INVITATION_AND_FRIEND": 2,
	"PRIVACY_LEVEL_OPEN_INVITATION":            3,
	"PRIVACY_LEVEL_CLOSED":                     4,
}

func (x ChannelState_PrivacyLevel) Enum() *ChannelState_PrivacyLevel {
	p := new(ChannelState_PrivacyLevel)
	*p = x
	return p
}
func (x ChannelState_PrivacyLevel) String() string {
	return proto.EnumName(ChannelState_PrivacyLevel_name, int32(x))
}
func (x *ChannelState_PrivacyLevel) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChannelState_PrivacyLevel_value, data, "ChannelState_PrivacyLevel")
	if err != nil {
		return err
	}
	*x = ChannelState_PrivacyLevel(value)
	return nil
}

type Message struct {
	Attribute        []*attribute.Attribute `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	Role             *uint32                `protobuf:"varint,2,opt,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetAttribute() []*attribute.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Message) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

type FindChannelOptions struct {
	StartIndex       *uint32                    `protobuf:"varint,1,opt,name=start_index,def=0" json:"start_index,omitempty"`
	MaxResults       *uint32                    `protobuf:"varint,2,opt,name=max_results,def=16" json:"max_results,omitempty"`
	Name             *string                    `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Program          *uint32                    `protobuf:"fixed32,4,opt,name=program" json:"program,omitempty"`
	Locale           *uint32                    `protobuf:"fixed32,5,opt,name=locale" json:"locale,omitempty"`
	CapacityFull     *uint32                    `protobuf:"varint,6,opt,name=capacity_full" json:"capacity_full,omitempty"`
	AttributeFilter  *attribute.AttributeFilter `protobuf:"bytes,7,req,name=attribute_filter" json:"attribute_filter,omitempty"`
	ChannelType      *string                    `protobuf:"bytes,8,opt,name=channel_type" json:"channel_type,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *FindChannelOptions) Reset()         { *m = FindChannelOptions{} }
func (m *FindChannelOptions) String() string { return proto.CompactTextString(m) }
func (*FindChannelOptions) ProtoMessage()    {}

const Default_FindChannelOptions_StartIndex uint32 = 0
const Default_FindChannelOptions_MaxResults uint32 = 16

func (m *FindChannelOptions) GetStartIndex() uint32 {
	if m != nil && m.StartIndex != nil {
		return *m.StartIndex
	}
	return Default_FindChannelOptions_StartIndex
}

func (m *FindChannelOptions) GetMaxResults() uint32 {
	if m != nil && m.MaxResults != nil {
		return *m.MaxResults
	}
	return Default_FindChannelOptions_MaxResults
}

func (m *FindChannelOptions) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FindChannelOptions) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

func (m *FindChannelOptions) GetLocale() uint32 {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return 0
}

func (m *FindChannelOptions) GetCapacityFull() uint32 {
	if m != nil && m.CapacityFull != nil {
		return *m.CapacityFull
	}
	return 0
}

func (m *FindChannelOptions) GetAttributeFilter() *attribute.AttributeFilter {
	if m != nil {
		return m.AttributeFilter
	}
	return nil
}

func (m *FindChannelOptions) GetChannelType() string {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return ""
}

type ChannelDescription struct {
	ChannelId        *entity.EntityId `protobuf:"bytes,1,req,name=channel_id" json:"channel_id,omitempty"`
	CurrentMembers   *uint32          `protobuf:"varint,2,opt,name=current_members" json:"current_members,omitempty"`
	State            *ChannelState    `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *ChannelDescription) Reset()         { *m = ChannelDescription{} }
func (m *ChannelDescription) String() string { return proto.CompactTextString(m) }
func (*ChannelDescription) ProtoMessage()    {}

func (m *ChannelDescription) GetChannelId() *entity.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *ChannelDescription) GetCurrentMembers() uint32 {
	if m != nil && m.CurrentMembers != nil {
		return *m.CurrentMembers
	}
	return 0
}

func (m *ChannelDescription) GetState() *ChannelState {
	if m != nil {
		return m.State
	}
	return nil
}

type ChannelInfo struct {
	Description      *ChannelDescription `protobuf:"bytes,1,req,name=description" json:"description,omitempty"`
	Member           []*Member           `protobuf:"bytes,2,rep,name=member" json:"member,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *ChannelInfo) Reset()         { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()    {}

func (m *ChannelInfo) GetDescription() *ChannelDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ChannelInfo) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type ChannelState struct {
	MaxMembers          *uint32                        `protobuf:"varint,1,opt,name=max_members" json:"max_members,omitempty"`
	MinMembers          *uint32                        `protobuf:"varint,2,opt,name=min_members" json:"min_members,omitempty"`
	Attribute           []*attribute.Attribute         `protobuf:"bytes,3,rep,name=attribute" json:"attribute,omitempty"`
	Invitation          []*invitation_types.Invitation `protobuf:"bytes,4,rep,name=invitation" json:"invitation,omitempty"`
	MaxInvitations      *uint32                        `protobuf:"varint,5,opt,name=max_invitations" json:"max_invitations,omitempty"`
	Reason              *uint32                        `protobuf:"varint,6,opt,name=reason" json:"reason,omitempty"`
	PrivacyLevel        *ChannelState_PrivacyLevel     `protobuf:"varint,7,opt,name=privacy_level,enum=channel_types.ChannelState_PrivacyLevel,def=1" json:"privacy_level,omitempty"`
	Name                *string                        `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`
	DelegateName        *string                        `protobuf:"bytes,9,opt,name=delegate_name" json:"delegate_name,omitempty"`
	ChannelType         *string                        `protobuf:"bytes,10,opt,name=channel_type,def=default" json:"channel_type,omitempty"`
	Program             *uint32                        `protobuf:"fixed32,11,opt,name=program,def=0" json:"program,omitempty"`
	AllowOfflineMembers *bool                          `protobuf:"varint,12,opt,name=allow_offline_members,def=0" json:"allow_offline_members,omitempty"`
	SubscribeToPresence *bool                          `protobuf:"varint,13,opt,name=subscribe_to_presence,def=1" json:"subscribe_to_presence,omitempty"`
	XXX_extensions      map[int32]proto.Extension      `json:"-"`
	XXX_unrecognized    []byte                         `json:"-"`
}

func (m *ChannelState) Reset()         { *m = ChannelState{} }
func (m *ChannelState) String() string { return proto.CompactTextString(m) }
func (*ChannelState) ProtoMessage()    {}

var extRange_ChannelState = []proto.ExtensionRange{
	{100, 10000},
}

func (*ChannelState) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_ChannelState
}
func (m *ChannelState) ExtensionMap() map[int32]proto.Extension {
	if m.XXX_extensions == nil {
		m.XXX_extensions = make(map[int32]proto.Extension)
	}
	return m.XXX_extensions
}

const Default_ChannelState_PrivacyLevel ChannelState_PrivacyLevel = ChannelState_PRIVACY_LEVEL_OPEN
const Default_ChannelState_ChannelType string = "default"
const Default_ChannelState_Program uint32 = 0
const Default_ChannelState_AllowOfflineMembers bool = false
const Default_ChannelState_SubscribeToPresence bool = true

func (m *ChannelState) GetMaxMembers() uint32 {
	if m != nil && m.MaxMembers != nil {
		return *m.MaxMembers
	}
	return 0
}

func (m *ChannelState) GetMinMembers() uint32 {
	if m != nil && m.MinMembers != nil {
		return *m.MinMembers
	}
	return 0
}

func (m *ChannelState) GetAttribute() []*attribute.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *ChannelState) GetInvitation() []*invitation_types.Invitation {
	if m != nil {
		return m.Invitation
	}
	return nil
}

func (m *ChannelState) GetMaxInvitations() uint32 {
	if m != nil && m.MaxInvitations != nil {
		return *m.MaxInvitations
	}
	return 0
}

func (m *ChannelState) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

func (m *ChannelState) GetPrivacyLevel() ChannelState_PrivacyLevel {
	if m != nil && m.PrivacyLevel != nil {
		return *m.PrivacyLevel
	}
	return Default_ChannelState_PrivacyLevel
}

func (m *ChannelState) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *ChannelState) GetDelegateName() string {
	if m != nil && m.DelegateName != nil {
		return *m.DelegateName
	}
	return ""
}

func (m *ChannelState) GetChannelType() string {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return Default_ChannelState_ChannelType
}

func (m *ChannelState) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return Default_ChannelState_Program
}

func (m *ChannelState) GetAllowOfflineMembers() bool {
	if m != nil && m.AllowOfflineMembers != nil {
		return *m.AllowOfflineMembers
	}
	return Default_ChannelState_AllowOfflineMembers
}

func (m *ChannelState) GetSubscribeToPresence() bool {
	if m != nil && m.SubscribeToPresence != nil {
		return *m.SubscribeToPresence
	}
	return Default_ChannelState_SubscribeToPresence
}

type MemberState struct {
	Attribute        []*attribute.Attribute `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	Role             []uint32               `protobuf:"varint,2,rep,packed,name=role" json:"role,omitempty"`
	Privileges       *uint64                `protobuf:"varint,3,opt,name=privileges,def=0" json:"privileges,omitempty"`
	Info             *entity.AccountInfo    `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Hidden           *bool                  `protobuf:"varint,5,opt,name=hidden,def=0" json:"hidden,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MemberState) Reset()         { *m = MemberState{} }
func (m *MemberState) String() string { return proto.CompactTextString(m) }
func (*MemberState) ProtoMessage()    {}

const Default_MemberState_Privileges uint64 = 0
const Default_MemberState_Hidden bool = false

func (m *MemberState) GetAttribute() []*attribute.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *MemberState) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *MemberState) GetPrivileges() uint64 {
	if m != nil && m.Privileges != nil {
		return *m.Privileges
	}
	return Default_MemberState_Privileges
}

func (m *MemberState) GetInfo() *entity.AccountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MemberState) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return Default_MemberState_Hidden
}

type Member struct {
	Identity         *entity.Identity `protobuf:"bytes,1,req,name=identity" json:"identity,omitempty"`
	State            *MemberState     `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}

func (m *Member) GetIdentity() *entity.Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Member) GetState() *MemberState {
	if m != nil {
		return m.State
	}
	return nil
}

func init() {
	proto.RegisterEnum("channel_types.ChannelState_PrivacyLevel", ChannelState_PrivacyLevel_name, ChannelState_PrivacyLevel_value)
}
