// Code generated by protoc-gen-go.
// source: bnet/protocol/authentication/authentication.proto
// DO NOT EDIT!

/*
Package bnet_protocol_authentication is a generated protocol buffer package.

It is generated from these files:
	bnet/protocol/authentication/authentication.proto

It has these top-level messages:
	AccountSettingsNotification
	GameAccountSelectedRequest
	GenerateSSOTokenRequest
	GenerateSSOTokenResponse
	LogonQueueUpdateRequest
	LogonRequest
	LogonResult
	LogonUpdateRequest
	MemModuleLoadRequest
	MemModuleLoadResponse
	ModuleLoadRequest
	ModuleMessageRequest
	ModuleNotification
	SelectGameAccountRequest
	ServerStateChangeRequest
	VerifyWebCredentialsRequest
	VersionInfo
	VersionInfoNotification
*/
package bnet_protocol_authentication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bnet_protocol_account "bnet/protocol/account"
import bnet_protocol "bnet/protocol"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ref: bnet.protocol.authentication.AccountSettingsNotification
type AccountSettingsNotification struct {
	Licenses         []*bnet_protocol_account.AccountLicense `protobuf:"bytes,1,rep,name=licenses" json:"licenses,omitempty"`
	IsUsingRid       bool                                    `protobuf:"varint,2,opt,name=is_using_rid,json=isUsingRid" json:"is_using_rid,omitempty"`
	IsPlayingFromIgr bool                                    `protobuf:"varint,3,opt,name=is_playing_from_igr,json=isPlayingFromIgr" json:"is_playing_from_igr,omitempty"`
	CanReceiveVoice  bool                                    `protobuf:"varint,4,opt,name=can_receive_voice,json=canReceiveVoice" json:"can_receive_voice,omitempty"`
	CanSendVoice     bool                                    `protobuf:"varint,5,opt,name=can_send_voice,json=canSendVoice" json:"can_send_voice,omitempty"`
}

func (m *AccountSettingsNotification) Reset()                    { *m = AccountSettingsNotification{} }
func (m *AccountSettingsNotification) String() string            { return proto.CompactTextString(m) }
func (*AccountSettingsNotification) ProtoMessage()               {}
func (*AccountSettingsNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AccountSettingsNotification) GetLicenses() []*bnet_protocol_account.AccountLicense {
	if m != nil {
		return m.Licenses
	}
	return nil
}

func (m *AccountSettingsNotification) GetIsUsingRid() bool {
	if m != nil {
		return m.IsUsingRid
	}
	return false
}

func (m *AccountSettingsNotification) GetIsPlayingFromIgr() bool {
	if m != nil {
		return m.IsPlayingFromIgr
	}
	return false
}

func (m *AccountSettingsNotification) GetCanReceiveVoice() bool {
	if m != nil {
		return m.CanReceiveVoice
	}
	return false
}

func (m *AccountSettingsNotification) GetCanSendVoice() bool {
	if m != nil {
		return m.CanSendVoice
	}
	return false
}

// ref: bnet.protocol.authentication.GameAccountSelectedRequest
type GameAccountSelectedRequest struct {
	Result      uint32                  `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
	GameAccount *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=game_account,json=gameAccount" json:"game_account,omitempty"`
}

func (m *GameAccountSelectedRequest) Reset()                    { *m = GameAccountSelectedRequest{} }
func (m *GameAccountSelectedRequest) String() string            { return proto.CompactTextString(m) }
func (*GameAccountSelectedRequest) ProtoMessage()               {}
func (*GameAccountSelectedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GameAccountSelectedRequest) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func (m *GameAccountSelectedRequest) GetGameAccount() *bnet_protocol.EntityId {
	if m != nil {
		return m.GameAccount
	}
	return nil
}

// ref: bnet.protocol.authentication.GenerateSSOTokenRequest
type GenerateSSOTokenRequest struct {
	Program uint32 `protobuf:"fixed32,1,opt,name=program" json:"program,omitempty"`
}

func (m *GenerateSSOTokenRequest) Reset()                    { *m = GenerateSSOTokenRequest{} }
func (m *GenerateSSOTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*GenerateSSOTokenRequest) ProtoMessage()               {}
func (*GenerateSSOTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GenerateSSOTokenRequest) GetProgram() uint32 {
	if m != nil {
		return m.Program
	}
	return 0
}

// ref: bnet.protocol.authentication.GenerateSSOTokenResponse
type GenerateSSOTokenResponse struct {
	SsoId     []byte `protobuf:"bytes,1,opt,name=sso_id,json=ssoId,proto3" json:"sso_id,omitempty"`
	SsoSecret []byte `protobuf:"bytes,2,opt,name=sso_secret,json=ssoSecret,proto3" json:"sso_secret,omitempty"`
}

func (m *GenerateSSOTokenResponse) Reset()                    { *m = GenerateSSOTokenResponse{} }
func (m *GenerateSSOTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*GenerateSSOTokenResponse) ProtoMessage()               {}
func (*GenerateSSOTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GenerateSSOTokenResponse) GetSsoId() []byte {
	if m != nil {
		return m.SsoId
	}
	return nil
}

func (m *GenerateSSOTokenResponse) GetSsoSecret() []byte {
	if m != nil {
		return m.SsoSecret
	}
	return nil
}

// ref: bnet.protocol.authentication.LogonQueueUpdateRequest
type LogonQueueUpdateRequest struct {
	Position          uint32 `protobuf:"varint,1,opt,name=position" json:"position,omitempty"`
	EstimatedTime     uint64 `protobuf:"varint,2,opt,name=estimated_time,json=estimatedTime" json:"estimated_time,omitempty"`
	EtaDeviationInSec uint64 `protobuf:"varint,3,opt,name=eta_deviation_in_sec,json=etaDeviationInSec" json:"eta_deviation_in_sec,omitempty"`
}

func (m *LogonQueueUpdateRequest) Reset()                    { *m = LogonQueueUpdateRequest{} }
func (m *LogonQueueUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*LogonQueueUpdateRequest) ProtoMessage()               {}
func (*LogonQueueUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *LogonQueueUpdateRequest) GetPosition() uint32 {
	if m != nil {
		return m.Position
	}
	return 0
}

func (m *LogonQueueUpdateRequest) GetEstimatedTime() uint64 {
	if m != nil {
		return m.EstimatedTime
	}
	return 0
}

func (m *LogonQueueUpdateRequest) GetEtaDeviationInSec() uint64 {
	if m != nil {
		return m.EtaDeviationInSec
	}
	return 0
}

// ref: bnet.protocol.authentication.LogonRequest
type LogonRequest struct {
	Program                      string `protobuf:"bytes,1,opt,name=program" json:"program,omitempty"`
	Platform                     string `protobuf:"bytes,2,opt,name=platform" json:"platform,omitempty"`
	Locale                       string `protobuf:"bytes,3,opt,name=locale" json:"locale,omitempty"`
	Email                        string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Version                      string `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	ApplicationVersion           int32  `protobuf:"varint,6,opt,name=application_version,json=applicationVersion" json:"application_version,omitempty"`
	PublicComputer               bool   `protobuf:"varint,7,opt,name=public_computer,json=publicComputer" json:"public_computer,omitempty"`
	SsoId                        []byte `protobuf:"bytes,8,opt,name=sso_id,json=ssoId,proto3" json:"sso_id,omitempty"`
	DisconnectOnCookieFail       bool   `protobuf:"varint,9,opt,name=disconnect_on_cookie_fail,json=disconnectOnCookieFail" json:"disconnect_on_cookie_fail,omitempty"`
	AllowLogonQueueNotifications bool   `protobuf:"varint,10,opt,name=allow_logon_queue_notifications,json=allowLogonQueueNotifications" json:"allow_logon_queue_notifications,omitempty"`
	WebClientVerification        bool   `protobuf:"varint,11,opt,name=web_client_verification,json=webClientVerification" json:"web_client_verification,omitempty"`
	CachedWebCredentials         []byte `protobuf:"bytes,12,opt,name=cached_web_credentials,json=cachedWebCredentials,proto3" json:"cached_web_credentials,omitempty"`
	UserAgent                    string `protobuf:"bytes,14,opt,name=user_agent,json=userAgent" json:"user_agent,omitempty"`
}

func (m *LogonRequest) Reset()                    { *m = LogonRequest{} }
func (m *LogonRequest) String() string            { return proto.CompactTextString(m) }
func (*LogonRequest) ProtoMessage()               {}
func (*LogonRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *LogonRequest) GetProgram() string {
	if m != nil {
		return m.Program
	}
	return ""
}

func (m *LogonRequest) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *LogonRequest) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

func (m *LogonRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LogonRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LogonRequest) GetApplicationVersion() int32 {
	if m != nil {
		return m.ApplicationVersion
	}
	return 0
}

func (m *LogonRequest) GetPublicComputer() bool {
	if m != nil {
		return m.PublicComputer
	}
	return false
}

func (m *LogonRequest) GetSsoId() []byte {
	if m != nil {
		return m.SsoId
	}
	return nil
}

func (m *LogonRequest) GetDisconnectOnCookieFail() bool {
	if m != nil {
		return m.DisconnectOnCookieFail
	}
	return false
}

func (m *LogonRequest) GetAllowLogonQueueNotifications() bool {
	if m != nil {
		return m.AllowLogonQueueNotifications
	}
	return false
}

func (m *LogonRequest) GetWebClientVerification() bool {
	if m != nil {
		return m.WebClientVerification
	}
	return false
}

func (m *LogonRequest) GetCachedWebCredentials() []byte {
	if m != nil {
		return m.CachedWebCredentials
	}
	return nil
}

func (m *LogonRequest) GetUserAgent() string {
	if m != nil {
		return m.UserAgent
	}
	return ""
}

// ref: bnet.protocol.authentication.LogonResult
type LogonResult struct {
	ErrorCode       uint32                    `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	Account         *bnet_protocol.EntityId   `protobuf:"bytes,2,opt,name=account" json:"account,omitempty"`
	GameAccount     []*bnet_protocol.EntityId `protobuf:"bytes,3,rep,name=game_account,json=gameAccount" json:"game_account,omitempty"`
	Email           string                    `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	AvailableRegion []uint32                  `protobuf:"varint,5,rep,name=available_region,json=availableRegion" json:"available_region,omitempty"`
	ConnectedRegion uint32                    `protobuf:"varint,6,opt,name=connected_region,json=connectedRegion" json:"connected_region,omitempty"`
	BattleTag       string                    `protobuf:"bytes,7,opt,name=battle_tag,json=battleTag" json:"battle_tag,omitempty"`
	GeoipCountry    string                    `protobuf:"bytes,8,opt,name=geoip_country,json=geoipCountry" json:"geoip_country,omitempty"`
}

func (m *LogonResult) Reset()                    { *m = LogonResult{} }
func (m *LogonResult) String() string            { return proto.CompactTextString(m) }
func (*LogonResult) ProtoMessage()               {}
func (*LogonResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *LogonResult) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *LogonResult) GetAccount() *bnet_protocol.EntityId {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *LogonResult) GetGameAccount() []*bnet_protocol.EntityId {
	if m != nil {
		return m.GameAccount
	}
	return nil
}

func (m *LogonResult) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LogonResult) GetAvailableRegion() []uint32 {
	if m != nil {
		return m.AvailableRegion
	}
	return nil
}

func (m *LogonResult) GetConnectedRegion() uint32 {
	if m != nil {
		return m.ConnectedRegion
	}
	return 0
}

func (m *LogonResult) GetBattleTag() string {
	if m != nil {
		return m.BattleTag
	}
	return ""
}

func (m *LogonResult) GetGeoipCountry() string {
	if m != nil {
		return m.GeoipCountry
	}
	return ""
}

// ref: bnet.protocol.authentication.LogonUpdateRequest
type LogonUpdateRequest struct {
	ErrorCode uint32 `protobuf:"varint,1,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
}

func (m *LogonUpdateRequest) Reset()                    { *m = LogonUpdateRequest{} }
func (m *LogonUpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*LogonUpdateRequest) ProtoMessage()               {}
func (*LogonUpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *LogonUpdateRequest) GetErrorCode() uint32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

// ref: bnet.protocol.authentication.MemModuleLoadRequest
type MemModuleLoadRequest struct {
	Handle *bnet_protocol.ContentHandle `protobuf:"bytes,1,opt,name=handle" json:"handle,omitempty"`
	Key    []byte                       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Input  []byte                       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
}

func (m *MemModuleLoadRequest) Reset()                    { *m = MemModuleLoadRequest{} }
func (m *MemModuleLoadRequest) String() string            { return proto.CompactTextString(m) }
func (*MemModuleLoadRequest) ProtoMessage()               {}
func (*MemModuleLoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MemModuleLoadRequest) GetHandle() *bnet_protocol.ContentHandle {
	if m != nil {
		return m.Handle
	}
	return nil
}

func (m *MemModuleLoadRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *MemModuleLoadRequest) GetInput() []byte {
	if m != nil {
		return m.Input
	}
	return nil
}

// ref: bnet.protocol.authentication.MemModuleLoadResponse
type MemModuleLoadResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *MemModuleLoadResponse) Reset()                    { *m = MemModuleLoadResponse{} }
func (m *MemModuleLoadResponse) String() string            { return proto.CompactTextString(m) }
func (*MemModuleLoadResponse) ProtoMessage()               {}
func (*MemModuleLoadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *MemModuleLoadResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// ref: bnet.protocol.authentication.ModuleLoadRequest
type ModuleLoadRequest struct {
	ModuleHandle *bnet_protocol.ContentHandle `protobuf:"bytes,1,opt,name=module_handle,json=moduleHandle" json:"module_handle,omitempty"`
	Message      []byte                       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *ModuleLoadRequest) Reset()                    { *m = ModuleLoadRequest{} }
func (m *ModuleLoadRequest) String() string            { return proto.CompactTextString(m) }
func (*ModuleLoadRequest) ProtoMessage()               {}
func (*ModuleLoadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ModuleLoadRequest) GetModuleHandle() *bnet_protocol.ContentHandle {
	if m != nil {
		return m.ModuleHandle
	}
	return nil
}

func (m *ModuleLoadRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// ref: bnet.protocol.authentication.ModuleMessageRequest
type ModuleMessageRequest struct {
	ModuleId int32  `protobuf:"varint,1,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
	Message  []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *ModuleMessageRequest) Reset()                    { *m = ModuleMessageRequest{} }
func (m *ModuleMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*ModuleMessageRequest) ProtoMessage()               {}
func (*ModuleMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ModuleMessageRequest) GetModuleId() int32 {
	if m != nil {
		return m.ModuleId
	}
	return 0
}

func (m *ModuleMessageRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// ref: bnet.protocol.authentication.ModuleNotification
type ModuleNotification struct {
	ModuleId int32  `protobuf:"varint,2,opt,name=module_id,json=moduleId" json:"module_id,omitempty"`
	Result   uint32 `protobuf:"varint,3,opt,name=result" json:"result,omitempty"`
}

func (m *ModuleNotification) Reset()                    { *m = ModuleNotification{} }
func (m *ModuleNotification) String() string            { return proto.CompactTextString(m) }
func (*ModuleNotification) ProtoMessage()               {}
func (*ModuleNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ModuleNotification) GetModuleId() int32 {
	if m != nil {
		return m.ModuleId
	}
	return 0
}

func (m *ModuleNotification) GetResult() uint32 {
	if m != nil {
		return m.Result
	}
	return 0
}

// ref: bnet.protocol.authentication.SelectGameAccountRequest
type SelectGameAccountRequest struct {
	GameAccount *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=game_account,json=gameAccount" json:"game_account,omitempty"`
}

func (m *SelectGameAccountRequest) Reset()                    { *m = SelectGameAccountRequest{} }
func (m *SelectGameAccountRequest) String() string            { return proto.CompactTextString(m) }
func (*SelectGameAccountRequest) ProtoMessage()               {}
func (*SelectGameAccountRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *SelectGameAccountRequest) GetGameAccount() *bnet_protocol.EntityId {
	if m != nil {
		return m.GameAccount
	}
	return nil
}

// ref: bnet.protocol.authentication.ServerStateChangeRequest
type ServerStateChangeRequest struct {
	State     uint32 `protobuf:"varint,1,opt,name=state" json:"state,omitempty"`
	EventTime uint64 `protobuf:"varint,2,opt,name=event_time,json=eventTime" json:"event_time,omitempty"`
}

func (m *ServerStateChangeRequest) Reset()                    { *m = ServerStateChangeRequest{} }
func (m *ServerStateChangeRequest) String() string            { return proto.CompactTextString(m) }
func (*ServerStateChangeRequest) ProtoMessage()               {}
func (*ServerStateChangeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ServerStateChangeRequest) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *ServerStateChangeRequest) GetEventTime() uint64 {
	if m != nil {
		return m.EventTime
	}
	return 0
}

// ref: bnet.protocol.authentication.VerifyWebCredentialsRequest
type VerifyWebCredentialsRequest struct {
	WebCredentials []byte `protobuf:"bytes,1,opt,name=web_credentials,json=webCredentials,proto3" json:"web_credentials,omitempty"`
}

func (m *VerifyWebCredentialsRequest) Reset()                    { *m = VerifyWebCredentialsRequest{} }
func (m *VerifyWebCredentialsRequest) String() string            { return proto.CompactTextString(m) }
func (*VerifyWebCredentialsRequest) ProtoMessage()               {}
func (*VerifyWebCredentialsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *VerifyWebCredentialsRequest) GetWebCredentials() []byte {
	if m != nil {
		return m.WebCredentials
	}
	return nil
}

// ref: bnet.protocol.authentication.VersionInfo
type VersionInfo struct {
	Number     uint32 `protobuf:"varint,1,opt,name=number" json:"number,omitempty"`
	Patch      string `protobuf:"bytes,2,opt,name=patch" json:"patch,omitempty"`
	IsOptional bool   `protobuf:"varint,3,opt,name=is_optional,json=isOptional" json:"is_optional,omitempty"`
	KickTime   uint64 `protobuf:"varint,4,opt,name=kick_time,json=kickTime" json:"kick_time,omitempty"`
}

func (m *VersionInfo) Reset()                    { *m = VersionInfo{} }
func (m *VersionInfo) String() string            { return proto.CompactTextString(m) }
func (*VersionInfo) ProtoMessage()               {}
func (*VersionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *VersionInfo) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *VersionInfo) GetPatch() string {
	if m != nil {
		return m.Patch
	}
	return ""
}

func (m *VersionInfo) GetIsOptional() bool {
	if m != nil {
		return m.IsOptional
	}
	return false
}

func (m *VersionInfo) GetKickTime() uint64 {
	if m != nil {
		return m.KickTime
	}
	return 0
}

// ref: bnet.protocol.authentication.VersionInfoNotification
type VersionInfoNotification struct {
	VersionInfo *VersionInfo `protobuf:"bytes,1,opt,name=version_info,json=versionInfo" json:"version_info,omitempty"`
}

func (m *VersionInfoNotification) Reset()                    { *m = VersionInfoNotification{} }
func (m *VersionInfoNotification) String() string            { return proto.CompactTextString(m) }
func (*VersionInfoNotification) ProtoMessage()               {}
func (*VersionInfoNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *VersionInfoNotification) GetVersionInfo() *VersionInfo {
	if m != nil {
		return m.VersionInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*AccountSettingsNotification)(nil), "bnet.protocol.authentication.AccountSettingsNotification")
	proto.RegisterType((*GameAccountSelectedRequest)(nil), "bnet.protocol.authentication.GameAccountSelectedRequest")
	proto.RegisterType((*GenerateSSOTokenRequest)(nil), "bnet.protocol.authentication.GenerateSSOTokenRequest")
	proto.RegisterType((*GenerateSSOTokenResponse)(nil), "bnet.protocol.authentication.GenerateSSOTokenResponse")
	proto.RegisterType((*LogonQueueUpdateRequest)(nil), "bnet.protocol.authentication.LogonQueueUpdateRequest")
	proto.RegisterType((*LogonRequest)(nil), "bnet.protocol.authentication.LogonRequest")
	proto.RegisterType((*LogonResult)(nil), "bnet.protocol.authentication.LogonResult")
	proto.RegisterType((*LogonUpdateRequest)(nil), "bnet.protocol.authentication.LogonUpdateRequest")
	proto.RegisterType((*MemModuleLoadRequest)(nil), "bnet.protocol.authentication.MemModuleLoadRequest")
	proto.RegisterType((*MemModuleLoadResponse)(nil), "bnet.protocol.authentication.MemModuleLoadResponse")
	proto.RegisterType((*ModuleLoadRequest)(nil), "bnet.protocol.authentication.ModuleLoadRequest")
	proto.RegisterType((*ModuleMessageRequest)(nil), "bnet.protocol.authentication.ModuleMessageRequest")
	proto.RegisterType((*ModuleNotification)(nil), "bnet.protocol.authentication.ModuleNotification")
	proto.RegisterType((*SelectGameAccountRequest)(nil), "bnet.protocol.authentication.SelectGameAccountRequest")
	proto.RegisterType((*ServerStateChangeRequest)(nil), "bnet.protocol.authentication.ServerStateChangeRequest")
	proto.RegisterType((*VerifyWebCredentialsRequest)(nil), "bnet.protocol.authentication.VerifyWebCredentialsRequest")
	proto.RegisterType((*VersionInfo)(nil), "bnet.protocol.authentication.VersionInfo")
	proto.RegisterType((*VersionInfoNotification)(nil), "bnet.protocol.authentication.VersionInfoNotification")
}

func init() { proto.RegisterFile("bnet/protocol/authentication/authentication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x56, 0x5b, 0x6f, 0x13, 0xc7,
	0x17, 0xff, 0x3b, 0x89, 0x93, 0xf8, 0xd8, 0xb9, 0x30, 0x04, 0xb2, 0xff, 0x10, 0x44, 0xb4, 0x14,
	0x11, 0x5a, 0x91, 0x88, 0x8b, 0x2a, 0xb5, 0x0f, 0x95, 0xa8, 0x0b, 0xd4, 0x52, 0xd2, 0xd0, 0x35,
	0xa4, 0x8f, 0xa3, 0xf1, 0xec, 0xc9, 0x66, 0x94, 0xdd, 0x99, 0x65, 0x67, 0xd6, 0x51, 0x3e, 0x41,
	0x5f, 0xda, 0x4f, 0xd7, 0x2f, 0x54, 0xcd, 0x65, 0x7d, 0x43, 0xa0, 0xf2, 0xe4, 0x3d, 0xbf, 0x73,
	0xbf, 0xcc, 0x39, 0x86, 0x67, 0x23, 0x89, 0xe6, 0xb8, 0xac, 0x94, 0x51, 0x5c, 0xe5, 0xc7, 0xac,
	0x36, 0x97, 0x28, 0x8d, 0xe0, 0xcc, 0x08, 0x25, 0x17, 0xc8, 0x23, 0x27, 0x46, 0xf6, 0xad, 0xca,
	0x51, 0xa3, 0x72, 0x34, 0x2f, 0xb3, 0xf7, 0x70, 0xc1, 0x20, 0xe7, 0xaa, 0x96, 0xa6, 0xf9, 0xf5,
	0x6a, 0x7b, 0xfb, 0xf3, 0x42, 0x13, 0x5b, 0xee, 0x23, 0xfe, 0x73, 0x09, 0xee, 0xbd, 0xf2, 0xf2,
	0x43, 0x34, 0x46, 0xc8, 0x4c, 0xff, 0xa6, 0x8c, 0xb8, 0x08, 0x2e, 0xc8, 0x6b, 0x58, 0xcf, 0x05,
	0x47, 0xa9, 0x51, 0x47, 0xad, 0x83, 0xe5, 0xc3, 0xee, 0xf3, 0x47, 0x47, 0x0b, 0x31, 0x05, 0x6f,
	0xc1, 0xca, 0x89, 0x97, 0xfe, 0x79, 0x69, 0xfb, 0x7f, 0xc9, 0x44, 0x95, 0x1c, 0x40, 0x4f, 0x68,
	0x5a, 0x6b, 0x21, 0x33, 0x5a, 0x89, 0x34, 0x5a, 0x3a, 0x68, 0x1d, 0xae, 0x27, 0x20, 0xf4, 0x07,
	0x0b, 0x25, 0x22, 0x25, 0x4f, 0xe1, 0xb6, 0xd0, 0xb4, 0xcc, 0xd9, 0x8d, 0x95, 0xb9, 0xa8, 0x54,
	0x41, 0x45, 0x56, 0x45, 0xcb, 0x4e, 0x70, 0x5b, 0xe8, 0x77, 0x9e, 0xf3, 0xa6, 0x52, 0xc5, 0x20,
	0xab, 0xc8, 0xb7, 0x70, 0x8b, 0x33, 0x49, 0x2b, 0xe4, 0x28, 0xc6, 0x48, 0xc7, 0x4a, 0x70, 0x8c,
	0x56, 0x9c, 0xf0, 0x16, 0x67, 0x32, 0xf1, 0xf8, 0xb9, 0x85, 0xc9, 0x37, 0xb0, 0x69, 0x65, 0x35,
	0xca, 0x34, 0x08, 0xb6, 0x9d, 0x60, 0x8f, 0x33, 0x39, 0x44, 0x99, 0x3a, 0xa9, 0xb8, 0x84, 0xbd,
	0xb7, 0xac, 0xc0, 0x49, 0x31, 0x72, 0xe4, 0x06, 0xd3, 0x04, 0x3f, 0xd6, 0xa8, 0x0d, 0xb9, 0x0b,
	0xab, 0x15, 0xea, 0x3a, 0x37, 0x51, 0xeb, 0xa0, 0x75, 0xb8, 0x91, 0x04, 0x8a, 0xfc, 0x08, 0xbd,
	0x8c, 0x15, 0x48, 0x43, 0x15, 0x5c, 0x62, 0xdd, 0xe7, 0xbb, 0x0b, 0x35, 0x7a, 0x2d, 0x8d, 0x30,
	0x37, 0x83, 0x34, 0xe9, 0x66, 0x53, 0x17, 0xf1, 0x0b, 0xd8, 0x7d, 0x8b, 0x12, 0x2b, 0x66, 0x70,
	0x38, 0x3c, 0x7b, 0xaf, 0xae, 0x50, 0x36, 0xee, 0x22, 0x58, 0x2b, 0x2b, 0x95, 0x55, 0xac, 0x70,
	0xfe, 0xd6, 0x92, 0x86, 0x8c, 0xdf, 0x41, 0xf4, 0xa9, 0x92, 0x2e, 0x95, 0xd4, 0x48, 0xee, 0xc0,
	0xaa, 0xd6, 0x8a, 0x8a, 0xd4, 0x29, 0xf5, 0x92, 0xb6, 0xd6, 0x6a, 0x90, 0x92, 0xfb, 0x00, 0x16,
	0xd6, 0xc8, 0x2b, 0xf4, 0x11, 0xf6, 0x92, 0x8e, 0xd6, 0x6a, 0xe8, 0x80, 0xf8, 0xef, 0x16, 0xec,
	0x9e, 0xa8, 0x4c, 0xc9, 0xdf, 0x6b, 0xac, 0xf1, 0x43, 0x99, 0x32, 0x83, 0x4d, 0x1c, 0x7b, 0xb0,
	0x5e, 0x2a, 0x2d, 0xec, 0x28, 0x84, 0xc4, 0x27, 0x34, 0x79, 0x04, 0x9b, 0xa8, 0x8d, 0x28, 0x98,
	0xc1, 0x94, 0x1a, 0x51, 0xa0, 0x33, 0xbd, 0x92, 0x6c, 0x4c, 0xd0, 0xf7, 0xa2, 0x40, 0x72, 0x0c,
	0x3b, 0x68, 0x18, 0x4d, 0x71, 0x2c, 0xdc, 0x48, 0x51, 0x61, 0x5b, 0xc1, 0x5d, 0x67, 0x57, 0x92,
	0x5b, 0x68, 0xd8, 0x2f, 0x0d, 0x6b, 0x20, 0x87, 0xc8, 0xe3, 0xbf, 0x56, 0xa0, 0xe7, 0xe2, 0xf9,
	0x4c, 0x31, 0x3a, 0x93, 0x62, 0xb8, 0xf0, 0x72, 0x66, 0x2e, 0x54, 0x55, 0x38, 0xe7, 0x9d, 0x64,
	0x42, 0xdb, 0x8e, 0xe5, 0x8a, 0xb3, 0x1c, 0x9d, 0xa7, 0x4e, 0x12, 0x28, 0xb2, 0x03, 0x6d, 0x2c,
	0x98, 0xc8, 0xdd, 0xb4, 0x74, 0x12, 0x4f, 0x58, 0x1f, 0x63, 0xac, 0xb4, 0xcd, 0xb3, 0xed, 0x7d,
	0x04, 0x92, 0x1c, 0xc3, 0x6d, 0x56, 0x96, 0x79, 0x78, 0x10, 0xb4, 0x91, 0x5a, 0x3d, 0x68, 0x1d,
	0xb6, 0x13, 0x32, 0xc3, 0x3a, 0x0f, 0x0a, 0x8f, 0x61, 0xab, 0xac, 0x47, 0xb9, 0xe0, 0x94, 0xab,
	0xa2, 0xac, 0x0d, 0x56, 0xd1, 0x9a, 0x9b, 0xb7, 0x4d, 0x0f, 0xf7, 0x03, 0x3a, 0xd3, 0xae, 0xf5,
	0xd9, 0x76, 0xfd, 0x00, 0xff, 0x4f, 0x85, 0xe6, 0x4a, 0x4a, 0xe4, 0x86, 0x2a, 0x49, 0xb9, 0x52,
	0x57, 0x02, 0xe9, 0x85, 0x0d, 0xba, 0xe3, 0x2c, 0xdd, 0x9d, 0x0a, 0x9c, 0xc9, 0xbe, 0x63, 0xbf,
	0xb1, 0x59, 0xbc, 0x86, 0x07, 0x2c, 0xcf, 0xd5, 0x35, 0xcd, 0x6d, 0xfd, 0xe8, 0x47, 0xdb, 0x50,
	0x2a, 0x67, 0xde, 0xb3, 0x8e, 0xc0, 0x19, 0xd8, 0x77, 0x62, 0xd3, 0xae, 0xcf, 0xbe, 0x79, 0x4d,
	0xbe, 0x87, 0xdd, 0x6b, 0x1c, 0x51, 0x9e, 0x0b, 0x94, 0xc6, 0x66, 0x3c, 0xe1, 0x45, 0x5d, 0xa7,
	0x7e, 0xe7, 0x1a, 0x47, 0x7d, 0xc7, 0x3d, 0x9f, 0x61, 0x92, 0x97, 0x70, 0x97, 0x33, 0x7e, 0x89,
	0x29, 0x75, 0xea, 0x15, 0xa6, 0x76, 0x59, 0xb1, 0x5c, 0x47, 0x3d, 0x97, 0xe0, 0x8e, 0xe7, 0xfe,
	0x81, 0xa3, 0xfe, 0x94, 0x67, 0xc7, 0xb3, 0xd6, 0x58, 0x51, 0x96, 0xa1, 0x34, 0xd1, 0xa6, 0xab,
	0x7e, 0xc7, 0x22, 0xaf, 0x2c, 0x10, 0xff, 0xb3, 0x04, 0xdd, 0x30, 0x0e, 0xee, 0xc5, 0xdd, 0x07,
	0xc0, 0xaa, 0x52, 0x15, 0xe5, 0x2a, 0xc5, 0x30, 0x94, 0x1d, 0x87, 0xf4, 0x55, 0x8a, 0xe4, 0x19,
	0xac, 0xfd, 0xc7, 0xb7, 0xd8, 0xc8, 0x91, 0x9f, 0x16, 0xde, 0xf0, 0xb2, 0xdb, 0x73, 0x9f, 0xd3,
	0x73, 0x9b, 0x6d, 0xf6, 0x1d, 0x7f, 0x66, 0xa2, 0x9e, 0xc2, 0x36, 0x1b, 0x33, 0x91, 0xb3, 0x51,
	0x8e, 0xb4, 0xc2, 0xcc, 0x8f, 0xd6, 0xf2, 0xe1, 0x86, 0x33, 0xb0, 0x35, 0xe1, 0x25, 0x8e, 0x45,
	0x9e, 0xc0, 0x76, 0xe8, 0x28, 0xa6, 0x8d, 0xf8, 0xaa, 0x4b, 0x6e, 0x6b, 0x82, 0x07, 0xd1, 0xfb,
	0x00, 0x23, 0x66, 0x4c, 0x8e, 0xd4, 0xb0, 0xcc, 0xcd, 0x56, 0x27, 0xe9, 0x78, 0xe4, 0x3d, 0xcb,
	0xc8, 0x43, 0xd8, 0xc8, 0x50, 0x89, 0x92, 0xba, 0xe8, 0xaa, 0x1b, 0x37, 0x5d, 0x9d, 0xa4, 0xe7,
	0xc0, 0xbe, 0xc7, 0xe2, 0x17, 0x40, 0x5c, 0x51, 0xe7, 0x9f, 0xfb, 0x97, 0x6b, 0x1b, 0x1b, 0xd8,
	0x39, 0xc5, 0xe2, 0x54, 0xa5, 0x75, 0x8e, 0x27, 0x8a, 0x4d, 0x96, 0xe3, 0x4b, 0x58, 0xbd, 0x64,
	0x32, 0xcd, 0xbd, 0x4a, 0xf7, 0xf9, 0xfe, 0x42, 0xe9, 0xfa, 0x4a, 0x1a, 0x94, 0xe6, 0x57, 0x27,
	0x93, 0x04, 0x59, 0xb2, 0x0d, 0xcb, 0x57, 0x78, 0x13, 0xf6, 0x91, 0xfd, 0xb4, 0x85, 0x14, 0xb2,
	0xac, 0x8d, 0x7b, 0xb1, 0xbd, 0xc4, 0x13, 0xf1, 0x77, 0x70, 0x67, 0xc1, 0x6b, 0x58, 0x77, 0x04,
	0x56, 0x52, 0x66, 0x58, 0x58, 0x76, 0xee, 0x3b, 0x2e, 0xe1, 0xd6, 0xa7, 0xf1, 0xbd, 0x82, 0x8d,
	0xc2, 0x81, 0xf4, 0x2b, 0xc2, 0xec, 0x79, 0x15, 0x4f, 0xd9, 0xfd, 0x50, 0xa0, 0xd6, 0x2c, 0xc3,
	0x10, 0x70, 0x43, 0xc6, 0xa7, 0xb0, 0xe3, 0x3d, 0x9e, 0x7a, 0xa0, 0x71, 0x7a, 0x0f, 0x3a, 0xc1,
	0x69, 0xd8, 0xc7, 0xed, 0x64, 0xdd, 0x03, 0x83, 0xf4, 0x0b, 0xe6, 0x06, 0x40, 0xbc, 0xb9, 0xb9,
	0x33, 0x3c, 0x67, 0x6c, 0x69, 0xc1, 0xd8, 0xf4, 0x36, 0x2d, 0xcf, 0xde, 0xa6, 0xf8, 0x1c, 0x22,
	0x7f, 0xc6, 0x66, 0xee, 0x5a, 0x13, 0xdd, 0xe2, 0xdd, 0x6a, 0x7d, 0xc5, 0xdd, 0x3a, 0xb3, 0x76,
	0xab, 0x31, 0x56, 0x43, 0xc3, 0x0c, 0xf6, 0x2f, 0x99, 0x9c, 0x66, 0xbd, 0x03, 0x6d, 0x6d, 0xd1,
	0x30, 0x3c, 0x9e, 0x70, 0x73, 0x35, 0xb6, 0xbb, 0x64, 0xe6, 0x4c, 0x74, 0x1c, 0x62, 0x4f, 0x44,
	0xfc, 0x06, 0xee, 0xb9, 0x3d, 0x72, 0x33, 0xbf, 0x19, 0x1a, 0x9b, 0x8f, 0x61, 0x6b, 0x71, 0x9f,
	0xf8, 0x96, 0x6f, 0x5e, 0xcf, 0xc9, 0xc7, 0x37, 0xd0, 0x0d, 0x4b, 0x78, 0x20, 0x2f, 0x94, 0xad,
	0x8b, 0xac, 0x8b, 0x11, 0x56, 0xcd, 0xcd, 0xf6, 0x94, 0x8d, 0xb1, 0x64, 0x86, 0x5f, 0x86, 0x93,
	0xe1, 0x09, 0xf2, 0x00, 0xba, 0x42, 0x53, 0x55, 0xda, 0x7a, 0xb3, 0x3c, 0xfc, 0xf1, 0x00, 0xa1,
	0xcf, 0x02, 0x62, 0x7b, 0x70, 0x25, 0xf8, 0x95, 0xcf, 0x61, 0xc5, 0xe5, 0xb0, 0x6e, 0x01, 0x97,
	0x42, 0x06, 0xbb, 0x33, 0xae, 0xe7, 0x7a, 0x77, 0x02, 0xbd, 0x70, 0x34, 0xa8, 0x90, 0x17, 0x2a,
	0x94, 0xfa, 0xc9, 0xd1, 0x97, 0xfe, 0xda, 0x1d, 0xcd, 0x18, 0x4b, 0xba, 0xe3, 0x29, 0x31, 0x5a,
	0x75, 0x1a, 0x2f, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x4f, 0xfd, 0x62, 0x16, 0x4d, 0x0a, 0x00,
	0x00,
}
