// Code generated by protoc-gen-go.
// source: bnet/protocol/channel/channel.proto
// DO NOT EDIT!

/*
Package bnet_protocol_channel is a generated protocol buffer package.

It is generated from these files:
	bnet/protocol/channel/channel.proto

It has these top-level messages:
	AddMemberRequest
	AddNotification
	ChannelInfo
	CreateChannelRequest
	CreateChannelResponse
	DissolveRequest
	FindChannelOptions
	FindChannelRequest
	FindChannelResponse
	GetChannelIdRequest
	GetChannelIdResponse
	GetChannelInfoRequest
	GetChannelInfoResponse
	JoinChannelRequest
	JoinChannelResponse
	JoinNotification
	LeaveNotification
	Member
	MemberState
	Message
	RemoveMemberRequest
	RemoveNotification
	SendMessageNotification
	SendMessageRequest
	SetRolesRequest
	SubscribeChannelRequest
	SubscribeChannelResponse
	UnsubscribeMemberRequest
	UpdateChannelStateNotification
	UpdateChannelStateRequest
	UpdateMemberStateNotification
	UpdateMemberStateRequest
*/
package bnet_protocol_channel

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import bnet_protocol_channel_extracted "github.com/HearthSim/hs-proto-go/bnet/protocol/channel/extracted"
import bnet_protocol "github.com/HearthSim/hs-proto-go/bnet/protocol"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AddMemberRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	MemberIdentity   *bnet_protocol.Identity `protobuf:"bytes,2,req,name=member_identity,json=memberIdentity" json:"member_identity,omitempty"`
	MemberState      *MemberState            `protobuf:"bytes,3,req,name=member_state,json=memberState" json:"member_state,omitempty"`
	ObjectId         *uint64                 `protobuf:"varint,4,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	Subscribe        *bool                   `protobuf:"varint,5,opt,name=subscribe,def=1" json:"subscribe,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *AddMemberRequest) Reset()                    { *m = AddMemberRequest{} }
func (m *AddMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*AddMemberRequest) ProtoMessage()               {}
func (*AddMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_AddMemberRequest_Subscribe bool = true

func (m *AddMemberRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *AddMemberRequest) GetMemberIdentity() *bnet_protocol.Identity {
	if m != nil {
		return m.MemberIdentity
	}
	return nil
}

func (m *AddMemberRequest) GetMemberState() *MemberState {
	if m != nil {
		return m.MemberState
	}
	return nil
}

func (m *AddMemberRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *AddMemberRequest) GetSubscribe() bool {
	if m != nil && m.Subscribe != nil {
		return *m.Subscribe
	}
	return Default_AddMemberRequest_Subscribe
}

type AddNotification struct {
	Self             *Member                                       `protobuf:"bytes,1,opt,name=self" json:"self,omitempty"`
	Member           []*Member                                     `protobuf:"bytes,2,rep,name=member" json:"member,omitempty"`
	ChannelState     *bnet_protocol_channel_extracted.ChannelState `protobuf:"bytes,3,req,name=channel_state,json=channelState" json:"channel_state,omitempty"`
	XXX_unrecognized []byte                                        `json:"-"`
}

func (m *AddNotification) Reset()                    { *m = AddNotification{} }
func (m *AddNotification) String() string            { return proto.CompactTextString(m) }
func (*AddNotification) ProtoMessage()               {}
func (*AddNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AddNotification) GetSelf() *Member {
	if m != nil {
		return m.Self
	}
	return nil
}

func (m *AddNotification) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

func (m *AddNotification) GetChannelState() *bnet_protocol_channel_extracted.ChannelState {
	if m != nil {
		return m.ChannelState
	}
	return nil
}

type ChannelInfo struct {
	Description      *bnet_protocol_channel_extracted.ChannelDescription `protobuf:"bytes,1,req,name=description" json:"description,omitempty"`
	Member           []*Member                                           `protobuf:"bytes,2,rep,name=member" json:"member,omitempty"`
	XXX_unrecognized []byte                                              `json:"-"`
}

func (m *ChannelInfo) Reset()                    { *m = ChannelInfo{} }
func (m *ChannelInfo) String() string            { return proto.CompactTextString(m) }
func (*ChannelInfo) ProtoMessage()               {}
func (*ChannelInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ChannelInfo) GetDescription() *bnet_protocol_channel_extracted.ChannelDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ChannelInfo) GetMember() []*Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type CreateChannelRequest struct {
	AgentIdentity    *bnet_protocol.Identity                       `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity" json:"agent_identity,omitempty"`
	MemberState      *MemberState                                  `protobuf:"bytes,2,opt,name=member_state,json=memberState" json:"member_state,omitempty"`
	ChannelState     *bnet_protocol_channel_extracted.ChannelState `protobuf:"bytes,3,opt,name=channel_state,json=channelState" json:"channel_state,omitempty"`
	ChannelId        *bnet_protocol.EntityId                       `protobuf:"bytes,4,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ObjectId         *uint64                                       `protobuf:"varint,5,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	LocalAgent       *bnet_protocol.EntityId                       `protobuf:"bytes,6,opt,name=local_agent,json=localAgent" json:"local_agent,omitempty"`
	LocalMemberState *MemberState                                  `protobuf:"bytes,7,opt,name=local_member_state,json=localMemberState" json:"local_member_state,omitempty"`
	XXX_unrecognized []byte                                        `json:"-"`
}

func (m *CreateChannelRequest) Reset()                    { *m = CreateChannelRequest{} }
func (m *CreateChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateChannelRequest) ProtoMessage()               {}
func (*CreateChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateChannelRequest) GetAgentIdentity() *bnet_protocol.Identity {
	if m != nil {
		return m.AgentIdentity
	}
	return nil
}

func (m *CreateChannelRequest) GetMemberState() *MemberState {
	if m != nil {
		return m.MemberState
	}
	return nil
}

func (m *CreateChannelRequest) GetChannelState() *bnet_protocol_channel_extracted.ChannelState {
	if m != nil {
		return m.ChannelState
	}
	return nil
}

func (m *CreateChannelRequest) GetChannelId() *bnet_protocol.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *CreateChannelRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *CreateChannelRequest) GetLocalAgent() *bnet_protocol.EntityId {
	if m != nil {
		return m.LocalAgent
	}
	return nil
}

func (m *CreateChannelRequest) GetLocalMemberState() *MemberState {
	if m != nil {
		return m.LocalMemberState
	}
	return nil
}

type CreateChannelResponse struct {
	ObjectId         *uint64                 `protobuf:"varint,1,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	ChannelId        *bnet_protocol.EntityId `protobuf:"bytes,2,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *CreateChannelResponse) Reset()                    { *m = CreateChannelResponse{} }
func (m *CreateChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateChannelResponse) ProtoMessage()               {}
func (*CreateChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateChannelResponse) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *CreateChannelResponse) GetChannelId() *bnet_protocol.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

type DissolveRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Reason           *uint32                 `protobuf:"varint,2,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *DissolveRequest) Reset()                    { *m = DissolveRequest{} }
func (m *DissolveRequest) String() string            { return proto.CompactTextString(m) }
func (*DissolveRequest) ProtoMessage()               {}
func (*DissolveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DissolveRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *DissolveRequest) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type FindChannelOptions struct {
	StartIndex       *uint32                        `protobuf:"varint,1,opt,name=start_index,json=startIndex,def=0" json:"start_index,omitempty"`
	MaxResults       *uint32                        `protobuf:"varint,2,opt,name=max_results,json=maxResults,def=16" json:"max_results,omitempty"`
	Name             *string                        `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Program          *uint32                        `protobuf:"fixed32,4,opt,name=program" json:"program,omitempty"`
	Locale           *uint32                        `protobuf:"fixed32,5,opt,name=locale" json:"locale,omitempty"`
	CapacityFull     *uint32                        `protobuf:"varint,6,opt,name=capacity_full,json=capacityFull" json:"capacity_full,omitempty"`
	AttributeFilter  *bnet_protocol.AttributeFilter `protobuf:"bytes,7,req,name=attribute_filter,json=attributeFilter" json:"attribute_filter,omitempty"`
	ChannelType      *string                        `protobuf:"bytes,8,opt,name=channel_type,json=channelType" json:"channel_type,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (m *FindChannelOptions) Reset()                    { *m = FindChannelOptions{} }
func (m *FindChannelOptions) String() string            { return proto.CompactTextString(m) }
func (*FindChannelOptions) ProtoMessage()               {}
func (*FindChannelOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

const Default_FindChannelOptions_StartIndex uint32 = 0
const Default_FindChannelOptions_MaxResults uint32 = 16

func (m *FindChannelOptions) GetStartIndex() uint32 {
	if m != nil && m.StartIndex != nil {
		return *m.StartIndex
	}
	return Default_FindChannelOptions_StartIndex
}

func (m *FindChannelOptions) GetMaxResults() uint32 {
	if m != nil && m.MaxResults != nil {
		return *m.MaxResults
	}
	return Default_FindChannelOptions_MaxResults
}

func (m *FindChannelOptions) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *FindChannelOptions) GetProgram() uint32 {
	if m != nil && m.Program != nil {
		return *m.Program
	}
	return 0
}

func (m *FindChannelOptions) GetLocale() uint32 {
	if m != nil && m.Locale != nil {
		return *m.Locale
	}
	return 0
}

func (m *FindChannelOptions) GetCapacityFull() uint32 {
	if m != nil && m.CapacityFull != nil {
		return *m.CapacityFull
	}
	return 0
}

func (m *FindChannelOptions) GetAttributeFilter() *bnet_protocol.AttributeFilter {
	if m != nil {
		return m.AttributeFilter
	}
	return nil
}

func (m *FindChannelOptions) GetChannelType() string {
	if m != nil && m.ChannelType != nil {
		return *m.ChannelType
	}
	return ""
}

type FindChannelRequest struct {
	AgentIdentity    *bnet_protocol.Identity `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity" json:"agent_identity,omitempty"`
	Options          *FindChannelOptions     `protobuf:"bytes,2,req,name=options" json:"options,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *FindChannelRequest) Reset()                    { *m = FindChannelRequest{} }
func (m *FindChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*FindChannelRequest) ProtoMessage()               {}
func (*FindChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FindChannelRequest) GetAgentIdentity() *bnet_protocol.Identity {
	if m != nil {
		return m.AgentIdentity
	}
	return nil
}

func (m *FindChannelRequest) GetOptions() *FindChannelOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

type FindChannelResponse struct {
	Channel          []*bnet_protocol_channel_extracted.ChannelDescription `protobuf:"bytes,1,rep,name=channel" json:"channel,omitempty"`
	XXX_unrecognized []byte                                                `json:"-"`
}

func (m *FindChannelResponse) Reset()                    { *m = FindChannelResponse{} }
func (m *FindChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*FindChannelResponse) ProtoMessage()               {}
func (*FindChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *FindChannelResponse) GetChannel() []*bnet_protocol_channel_extracted.ChannelDescription {
	if m != nil {
		return m.Channel
	}
	return nil
}

type GetChannelIdRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetChannelIdRequest) Reset()                    { *m = GetChannelIdRequest{} }
func (m *GetChannelIdRequest) String() string            { return proto.CompactTextString(m) }
func (*GetChannelIdRequest) ProtoMessage()               {}
func (*GetChannelIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type GetChannelIdResponse struct {
	ChannelId        *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetChannelIdResponse) Reset()                    { *m = GetChannelIdResponse{} }
func (m *GetChannelIdResponse) String() string            { return proto.CompactTextString(m) }
func (*GetChannelIdResponse) ProtoMessage()               {}
func (*GetChannelIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetChannelIdResponse) GetChannelId() *bnet_protocol.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

type GetChannelInfoRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ChannelId        *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	FetchState       *bool                   `protobuf:"varint,3,opt,name=fetch_state,json=fetchState,def=0" json:"fetch_state,omitempty"`
	FetchMembers     *bool                   `protobuf:"varint,4,opt,name=fetch_members,json=fetchMembers,def=0" json:"fetch_members,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *GetChannelInfoRequest) Reset()                    { *m = GetChannelInfoRequest{} }
func (m *GetChannelInfoRequest) String() string            { return proto.CompactTextString(m) }
func (*GetChannelInfoRequest) ProtoMessage()               {}
func (*GetChannelInfoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

const Default_GetChannelInfoRequest_FetchState bool = false
const Default_GetChannelInfoRequest_FetchMembers bool = false

func (m *GetChannelInfoRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *GetChannelInfoRequest) GetChannelId() *bnet_protocol.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *GetChannelInfoRequest) GetFetchState() bool {
	if m != nil && m.FetchState != nil {
		return *m.FetchState
	}
	return Default_GetChannelInfoRequest_FetchState
}

func (m *GetChannelInfoRequest) GetFetchMembers() bool {
	if m != nil && m.FetchMembers != nil {
		return *m.FetchMembers
	}
	return Default_GetChannelInfoRequest_FetchMembers
}

type GetChannelInfoResponse struct {
	ChannelInfo      *ChannelInfo `protobuf:"bytes,1,opt,name=channel_info,json=channelInfo" json:"channel_info,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GetChannelInfoResponse) Reset()                    { *m = GetChannelInfoResponse{} }
func (m *GetChannelInfoResponse) String() string            { return proto.CompactTextString(m) }
func (*GetChannelInfoResponse) ProtoMessage()               {}
func (*GetChannelInfoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *GetChannelInfoResponse) GetChannelInfo() *ChannelInfo {
	if m != nil {
		return m.ChannelInfo
	}
	return nil
}

type JoinChannelRequest struct {
	AgentIdentity    *bnet_protocol.Identity   `protobuf:"bytes,1,opt,name=agent_identity,json=agentIdentity" json:"agent_identity,omitempty"`
	MemberState      *MemberState              `protobuf:"bytes,2,opt,name=member_state,json=memberState" json:"member_state,omitempty"`
	ChannelId        *bnet_protocol.EntityId   `protobuf:"bytes,3,req,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ObjectId         *uint64                   `protobuf:"varint,4,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	FriendAccountId  []*bnet_protocol.EntityId `protobuf:"bytes,5,rep,name=friend_account_id,json=friendAccountId" json:"friend_account_id,omitempty"`
	LocalSubscriber  *bool                     `protobuf:"varint,6,opt,name=local_subscriber,json=localSubscriber,def=1" json:"local_subscriber,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *JoinChannelRequest) Reset()                    { *m = JoinChannelRequest{} }
func (m *JoinChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*JoinChannelRequest) ProtoMessage()               {}
func (*JoinChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

const Default_JoinChannelRequest_LocalSubscriber bool = true

func (m *JoinChannelRequest) GetAgentIdentity() *bnet_protocol.Identity {
	if m != nil {
		return m.AgentIdentity
	}
	return nil
}

func (m *JoinChannelRequest) GetMemberState() *MemberState {
	if m != nil {
		return m.MemberState
	}
	return nil
}

func (m *JoinChannelRequest) GetChannelId() *bnet_protocol.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *JoinChannelRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *JoinChannelRequest) GetFriendAccountId() []*bnet_protocol.EntityId {
	if m != nil {
		return m.FriendAccountId
	}
	return nil
}

func (m *JoinChannelRequest) GetLocalSubscriber() bool {
	if m != nil && m.LocalSubscriber != nil {
		return *m.LocalSubscriber
	}
	return Default_JoinChannelRequest_LocalSubscriber
}

type JoinChannelResponse struct {
	ObjectId                *uint64                   `protobuf:"varint,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	RequireFriendValidation *bool                     `protobuf:"varint,2,opt,name=require_friend_validation,json=requireFriendValidation,def=0" json:"require_friend_validation,omitempty"`
	PrivilegedAccount       []*bnet_protocol.EntityId `protobuf:"bytes,3,rep,name=privileged_account,json=privilegedAccount" json:"privileged_account,omitempty"`
	XXX_unrecognized        []byte                    `json:"-"`
}

func (m *JoinChannelResponse) Reset()                    { *m = JoinChannelResponse{} }
func (m *JoinChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*JoinChannelResponse) ProtoMessage()               {}
func (*JoinChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

const Default_JoinChannelResponse_RequireFriendValidation bool = false

func (m *JoinChannelResponse) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

func (m *JoinChannelResponse) GetRequireFriendValidation() bool {
	if m != nil && m.RequireFriendValidation != nil {
		return *m.RequireFriendValidation
	}
	return Default_JoinChannelResponse_RequireFriendValidation
}

func (m *JoinChannelResponse) GetPrivilegedAccount() []*bnet_protocol.EntityId {
	if m != nil {
		return m.PrivilegedAccount
	}
	return nil
}

type JoinNotification struct {
	Member           *Member `protobuf:"bytes,1,req,name=member" json:"member,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *JoinNotification) Reset()                    { *m = JoinNotification{} }
func (m *JoinNotification) String() string            { return proto.CompactTextString(m) }
func (*JoinNotification) ProtoMessage()               {}
func (*JoinNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *JoinNotification) GetMember() *Member {
	if m != nil {
		return m.Member
	}
	return nil
}

type LeaveNotification struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	MemberId         *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=member_id,json=memberId" json:"member_id,omitempty"`
	Reason           *uint32                 `protobuf:"varint,3,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *LeaveNotification) Reset()                    { *m = LeaveNotification{} }
func (m *LeaveNotification) String() string            { return proto.CompactTextString(m) }
func (*LeaveNotification) ProtoMessage()               {}
func (*LeaveNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *LeaveNotification) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *LeaveNotification) GetMemberId() *bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *LeaveNotification) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type Member struct {
	Identity         *bnet_protocol.Identity `protobuf:"bytes,1,req,name=identity" json:"identity,omitempty"`
	State            *MemberState            `protobuf:"bytes,2,req,name=state" json:"state,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Member) Reset()                    { *m = Member{} }
func (m *Member) String() string            { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()               {}
func (*Member) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Member) GetIdentity() *bnet_protocol.Identity {
	if m != nil {
		return m.Identity
	}
	return nil
}

func (m *Member) GetState() *MemberState {
	if m != nil {
		return m.State
	}
	return nil
}

type MemberState struct {
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	Role             []uint32                   `protobuf:"varint,2,rep,packed,name=role" json:"role,omitempty"`
	Privileges       *uint64                    `protobuf:"varint,3,opt,name=privileges,def=0" json:"privileges,omitempty"`
	Info             *bnet_protocol.AccountInfo `protobuf:"bytes,4,opt,name=info" json:"info,omitempty"`
	Hidden           *bool                      `protobuf:"varint,5,opt,name=hidden,def=0" json:"hidden,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *MemberState) Reset()                    { *m = MemberState{} }
func (m *MemberState) String() string            { return proto.CompactTextString(m) }
func (*MemberState) ProtoMessage()               {}
func (*MemberState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

const Default_MemberState_Privileges uint64 = 0
const Default_MemberState_Hidden bool = false

func (m *MemberState) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *MemberState) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *MemberState) GetPrivileges() uint64 {
	if m != nil && m.Privileges != nil {
		return *m.Privileges
	}
	return Default_MemberState_Privileges
}

func (m *MemberState) GetInfo() *bnet_protocol.AccountInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *MemberState) GetHidden() bool {
	if m != nil && m.Hidden != nil {
		return *m.Hidden
	}
	return Default_MemberState_Hidden
}

type Message struct {
	Attribute        []*bnet_protocol.Attribute `protobuf:"bytes,1,rep,name=attribute" json:"attribute,omitempty"`
	Role             *uint32                    `protobuf:"varint,2,opt,name=role" json:"role,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Message) GetAttribute() []*bnet_protocol.Attribute {
	if m != nil {
		return m.Attribute
	}
	return nil
}

func (m *Message) GetRole() uint32 {
	if m != nil && m.Role != nil {
		return *m.Role
	}
	return 0
}

type RemoveMemberRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	MemberId         *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=member_id,json=memberId" json:"member_id,omitempty"`
	Reason           *uint32                 `protobuf:"varint,3,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RemoveMemberRequest) Reset()                    { *m = RemoveMemberRequest{} }
func (m *RemoveMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*RemoveMemberRequest) ProtoMessage()               {}
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *RemoveMemberRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *RemoveMemberRequest) GetMemberId() *bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *RemoveMemberRequest) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type RemoveNotification struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	MemberId         *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=member_id,json=memberId" json:"member_id,omitempty"`
	Reason           *uint32                 `protobuf:"varint,3,opt,name=reason" json:"reason,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *RemoveNotification) Reset()                    { *m = RemoveNotification{} }
func (m *RemoveNotification) String() string            { return proto.CompactTextString(m) }
func (*RemoveNotification) ProtoMessage()               {}
func (*RemoveNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *RemoveNotification) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *RemoveNotification) GetMemberId() *bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

func (m *RemoveNotification) GetReason() uint32 {
	if m != nil && m.Reason != nil {
		return *m.Reason
	}
	return 0
}

type SendMessageNotification struct {
	AgentId            *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Message            *Message                `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	RequiredPrivileges *uint64                 `protobuf:"varint,3,opt,name=required_privileges,json=requiredPrivileges,def=0" json:"required_privileges,omitempty"`
	XXX_unrecognized   []byte                  `json:"-"`
}

func (m *SendMessageNotification) Reset()                    { *m = SendMessageNotification{} }
func (m *SendMessageNotification) String() string            { return proto.CompactTextString(m) }
func (*SendMessageNotification) ProtoMessage()               {}
func (*SendMessageNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

const Default_SendMessageNotification_RequiredPrivileges uint64 = 0

func (m *SendMessageNotification) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SendMessageNotification) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendMessageNotification) GetRequiredPrivileges() uint64 {
	if m != nil && m.RequiredPrivileges != nil {
		return *m.RequiredPrivileges
	}
	return Default_SendMessageNotification_RequiredPrivileges
}

type SendMessageRequest struct {
	AgentId            *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Message            *Message                `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	RequiredPrivileges *uint64                 `protobuf:"varint,3,opt,name=required_privileges,json=requiredPrivileges,def=0" json:"required_privileges,omitempty"`
	XXX_unrecognized   []byte                  `json:"-"`
}

func (m *SendMessageRequest) Reset()                    { *m = SendMessageRequest{} }
func (m *SendMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*SendMessageRequest) ProtoMessage()               {}
func (*SendMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

const Default_SendMessageRequest_RequiredPrivileges uint64 = 0

func (m *SendMessageRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SendMessageRequest) GetMessage() *Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *SendMessageRequest) GetRequiredPrivileges() uint64 {
	if m != nil && m.RequiredPrivileges != nil {
		return *m.RequiredPrivileges
	}
	return Default_SendMessageRequest_RequiredPrivileges
}

type SetRolesRequest struct {
	AgentId          *bnet_protocol.EntityId   `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	Role             []uint32                  `protobuf:"varint,2,rep,packed,name=role" json:"role,omitempty"`
	MemberId         []*bnet_protocol.EntityId `protobuf:"bytes,3,rep,name=member_id,json=memberId" json:"member_id,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *SetRolesRequest) Reset()                    { *m = SetRolesRequest{} }
func (m *SetRolesRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRolesRequest) ProtoMessage()               {}
func (*SetRolesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *SetRolesRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SetRolesRequest) GetRole() []uint32 {
	if m != nil {
		return m.Role
	}
	return nil
}

func (m *SetRolesRequest) GetMemberId() []*bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

type SubscribeChannelRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	ChannelId        *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	ObjectId         *uint64                 `protobuf:"varint,3,req,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *SubscribeChannelRequest) Reset()                    { *m = SubscribeChannelRequest{} }
func (m *SubscribeChannelRequest) String() string            { return proto.CompactTextString(m) }
func (*SubscribeChannelRequest) ProtoMessage()               {}
func (*SubscribeChannelRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *SubscribeChannelRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *SubscribeChannelRequest) GetChannelId() *bnet_protocol.EntityId {
	if m != nil {
		return m.ChannelId
	}
	return nil
}

func (m *SubscribeChannelRequest) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type SubscribeChannelResponse struct {
	ObjectId         *uint64 `protobuf:"varint,1,opt,name=object_id,json=objectId" json:"object_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *SubscribeChannelResponse) Reset()                    { *m = SubscribeChannelResponse{} }
func (m *SubscribeChannelResponse) String() string            { return proto.CompactTextString(m) }
func (*SubscribeChannelResponse) ProtoMessage()               {}
func (*SubscribeChannelResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *SubscribeChannelResponse) GetObjectId() uint64 {
	if m != nil && m.ObjectId != nil {
		return *m.ObjectId
	}
	return 0
}

type UnsubscribeMemberRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	MemberId         *bnet_protocol.EntityId `protobuf:"bytes,2,req,name=member_id,json=memberId" json:"member_id,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UnsubscribeMemberRequest) Reset()                    { *m = UnsubscribeMemberRequest{} }
func (m *UnsubscribeMemberRequest) String() string            { return proto.CompactTextString(m) }
func (*UnsubscribeMemberRequest) ProtoMessage()               {}
func (*UnsubscribeMemberRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *UnsubscribeMemberRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UnsubscribeMemberRequest) GetMemberId() *bnet_protocol.EntityId {
	if m != nil {
		return m.MemberId
	}
	return nil
}

type UpdateChannelStateNotification struct {
	AgentId          *bnet_protocol.EntityId                       `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	StateChange      *bnet_protocol_channel_extracted.ChannelState `protobuf:"bytes,2,req,name=state_change,json=stateChange" json:"state_change,omitempty"`
	XXX_unrecognized []byte                                        `json:"-"`
}

func (m *UpdateChannelStateNotification) Reset()                    { *m = UpdateChannelStateNotification{} }
func (m *UpdateChannelStateNotification) String() string            { return proto.CompactTextString(m) }
func (*UpdateChannelStateNotification) ProtoMessage()               {}
func (*UpdateChannelStateNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

func (m *UpdateChannelStateNotification) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UpdateChannelStateNotification) GetStateChange() *bnet_protocol_channel_extracted.ChannelState {
	if m != nil {
		return m.StateChange
	}
	return nil
}

type UpdateChannelStateRequest struct {
	AgentId          *bnet_protocol.EntityId                       `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	StateChange      *bnet_protocol_channel_extracted.ChannelState `protobuf:"bytes,2,req,name=state_change,json=stateChange" json:"state_change,omitempty"`
	XXX_unrecognized []byte                                        `json:"-"`
}

func (m *UpdateChannelStateRequest) Reset()                    { *m = UpdateChannelStateRequest{} }
func (m *UpdateChannelStateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateChannelStateRequest) ProtoMessage()               {}
func (*UpdateChannelStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func (m *UpdateChannelStateRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UpdateChannelStateRequest) GetStateChange() *bnet_protocol_channel_extracted.ChannelState {
	if m != nil {
		return m.StateChange
	}
	return nil
}

type UpdateMemberStateNotification struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	StateChange      []*Member               `protobuf:"bytes,2,rep,name=state_change,json=stateChange" json:"state_change,omitempty"`
	RemovedRole      []uint32                `protobuf:"varint,3,rep,packed,name=removed_role,json=removedRole" json:"removed_role,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdateMemberStateNotification) Reset()                    { *m = UpdateMemberStateNotification{} }
func (m *UpdateMemberStateNotification) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberStateNotification) ProtoMessage()               {}
func (*UpdateMemberStateNotification) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{30} }

func (m *UpdateMemberStateNotification) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UpdateMemberStateNotification) GetStateChange() []*Member {
	if m != nil {
		return m.StateChange
	}
	return nil
}

func (m *UpdateMemberStateNotification) GetRemovedRole() []uint32 {
	if m != nil {
		return m.RemovedRole
	}
	return nil
}

type UpdateMemberStateRequest struct {
	AgentId          *bnet_protocol.EntityId `protobuf:"bytes,1,opt,name=agent_id,json=agentId" json:"agent_id,omitempty"`
	StateChange      []*Member               `protobuf:"bytes,2,rep,name=state_change,json=stateChange" json:"state_change,omitempty"`
	RemovedRole      []uint32                `protobuf:"varint,3,rep,packed,name=removed_role,json=removedRole" json:"removed_role,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *UpdateMemberStateRequest) Reset()                    { *m = UpdateMemberStateRequest{} }
func (m *UpdateMemberStateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateMemberStateRequest) ProtoMessage()               {}
func (*UpdateMemberStateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{31} }

func (m *UpdateMemberStateRequest) GetAgentId() *bnet_protocol.EntityId {
	if m != nil {
		return m.AgentId
	}
	return nil
}

func (m *UpdateMemberStateRequest) GetStateChange() []*Member {
	if m != nil {
		return m.StateChange
	}
	return nil
}

func (m *UpdateMemberStateRequest) GetRemovedRole() []uint32 {
	if m != nil {
		return m.RemovedRole
	}
	return nil
}

func init() {
	proto.RegisterType((*AddMemberRequest)(nil), "bnet.protocol.channel.AddMemberRequest")
	proto.RegisterType((*AddNotification)(nil), "bnet.protocol.channel.AddNotification")
	proto.RegisterType((*ChannelInfo)(nil), "bnet.protocol.channel.ChannelInfo")
	proto.RegisterType((*CreateChannelRequest)(nil), "bnet.protocol.channel.CreateChannelRequest")
	proto.RegisterType((*CreateChannelResponse)(nil), "bnet.protocol.channel.CreateChannelResponse")
	proto.RegisterType((*DissolveRequest)(nil), "bnet.protocol.channel.DissolveRequest")
	proto.RegisterType((*FindChannelOptions)(nil), "bnet.protocol.channel.FindChannelOptions")
	proto.RegisterType((*FindChannelRequest)(nil), "bnet.protocol.channel.FindChannelRequest")
	proto.RegisterType((*FindChannelResponse)(nil), "bnet.protocol.channel.FindChannelResponse")
	proto.RegisterType((*GetChannelIdRequest)(nil), "bnet.protocol.channel.GetChannelIdRequest")
	proto.RegisterType((*GetChannelIdResponse)(nil), "bnet.protocol.channel.GetChannelIdResponse")
	proto.RegisterType((*GetChannelInfoRequest)(nil), "bnet.protocol.channel.GetChannelInfoRequest")
	proto.RegisterType((*GetChannelInfoResponse)(nil), "bnet.protocol.channel.GetChannelInfoResponse")
	proto.RegisterType((*JoinChannelRequest)(nil), "bnet.protocol.channel.JoinChannelRequest")
	proto.RegisterType((*JoinChannelResponse)(nil), "bnet.protocol.channel.JoinChannelResponse")
	proto.RegisterType((*JoinNotification)(nil), "bnet.protocol.channel.JoinNotification")
	proto.RegisterType((*LeaveNotification)(nil), "bnet.protocol.channel.LeaveNotification")
	proto.RegisterType((*Member)(nil), "bnet.protocol.channel.Member")
	proto.RegisterType((*MemberState)(nil), "bnet.protocol.channel.MemberState")
	proto.RegisterType((*Message)(nil), "bnet.protocol.channel.Message")
	proto.RegisterType((*RemoveMemberRequest)(nil), "bnet.protocol.channel.RemoveMemberRequest")
	proto.RegisterType((*RemoveNotification)(nil), "bnet.protocol.channel.RemoveNotification")
	proto.RegisterType((*SendMessageNotification)(nil), "bnet.protocol.channel.SendMessageNotification")
	proto.RegisterType((*SendMessageRequest)(nil), "bnet.protocol.channel.SendMessageRequest")
	proto.RegisterType((*SetRolesRequest)(nil), "bnet.protocol.channel.SetRolesRequest")
	proto.RegisterType((*SubscribeChannelRequest)(nil), "bnet.protocol.channel.SubscribeChannelRequest")
	proto.RegisterType((*SubscribeChannelResponse)(nil), "bnet.protocol.channel.SubscribeChannelResponse")
	proto.RegisterType((*UnsubscribeMemberRequest)(nil), "bnet.protocol.channel.UnsubscribeMemberRequest")
	proto.RegisterType((*UpdateChannelStateNotification)(nil), "bnet.protocol.channel.UpdateChannelStateNotification")
	proto.RegisterType((*UpdateChannelStateRequest)(nil), "bnet.protocol.channel.UpdateChannelStateRequest")
	proto.RegisterType((*UpdateMemberStateNotification)(nil), "bnet.protocol.channel.UpdateMemberStateNotification")
	proto.RegisterType((*UpdateMemberStateRequest)(nil), "bnet.protocol.channel.UpdateMemberStateRequest")
}

func init() { proto.RegisterFile("bnet/protocol/channel/channel.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1360 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xcc, 0x58, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0xd7, 0xd8, 0x6e, 0xec, 0xbc, 0x8d, 0xeb, 0x74, 0xd2, 0xb4, 0xdb, 0x42, 0xab, 0x74, 0x2a,
	0x50, 0x41, 0xc2, 0xa5, 0x2d, 0xb4, 0x55, 0x0e, 0xa8, 0x21, 0x6d, 0x90, 0x11, 0x29, 0xd5, 0x84,
	0x70, 0x43, 0xab, 0xcd, 0xce, 0x38, 0x5d, 0xb4, 0xde, 0x75, 0x77, 0xc7, 0x21, 0xb9, 0xf3, 0x01,
	0x90, 0x10, 0x20, 0xc4, 0x09, 0x0e, 0x7c, 0x84, 0x72, 0x00, 0x3e, 0x03, 0x12, 0x17, 0xbe, 0x01,
	0x9f, 0x03, 0xed, 0x9b, 0xd9, 0xf5, 0xae, 0x63, 0xbb, 0x6e, 0x5c, 0x95, 0x9e, 0xe2, 0x79, 0xf3,
	0xde, 0x9b, 0xdf, 0xbc, 0xf9, 0xbd, 0x3f, 0x1b, 0xb8, 0xba, 0x17, 0x4a, 0x75, 0xbd, 0x1f, 0x47,
	0x2a, 0xf2, 0xa2, 0xe0, 0xba, 0xf7, 0xd8, 0x0d, 0x43, 0x99, 0xff, 0x6d, 0xe3, 0x06, 0x5d, 0x4d,
	0x95, 0xda, 0x99, 0x52, 0xdb, 0x6c, 0x5e, 0xbc, 0x33, 0xde, 0x56, 0x1e, 0xaa, 0xd8, 0xf5, 0x94,
	0x14, 0xb9, 0x97, 0x5c, 0xa2, 0x7d, 0x5c, 0x7c, 0xbd, 0x6c, 0x98, 0x3b, 0xc6, 0x1f, 0xec, 0x9b,
	0x0a, 0x2c, 0x6f, 0x08, 0xb1, 0x2d, 0x7b, 0x7b, 0x32, 0xe6, 0xf2, 0xc9, 0x40, 0x26, 0x8a, 0xde,
	0x84, 0x86, 0xbb, 0x2f, 0x43, 0xe5, 0xf8, 0xc2, 0x26, 0x6b, 0xe4, 0x9a, 0x75, 0xf3, 0x7c, 0xbb,
	0x8c, 0xea, 0x41, 0xa8, 0x7c, 0x75, 0xd4, 0x11, 0xbc, 0x8e, 0x8a, 0x1d, 0x41, 0xef, 0x41, 0xab,
	0x87, 0x4e, 0x1c, 0x5f, 0x48, 0xdc, 0xb5, 0x2b, 0x6b, 0x95, 0x31, 0xa6, 0x1d, 0xb3, 0xcd, 0x4f,
	0x6b, 0xfd, 0x6c, 0x4d, 0x1f, 0xc0, 0x92, 0xf1, 0x90, 0x28, 0x57, 0x49, 0xbb, 0x8a, 0xe6, 0xac,
	0x3d, 0x36, 0x1e, 0x6d, 0x8d, 0x78, 0x27, 0xd5, 0xe4, 0x56, 0x6f, 0xb8, 0xa0, 0xaf, 0xc1, 0x62,
	0xb4, 0xf7, 0xa5, 0xf4, 0x10, 0x7d, 0x6d, 0xad, 0x72, 0xad, 0xc6, 0x1b, 0x5a, 0xd0, 0x11, 0x94,
	0xc1, 0x62, 0x32, 0xd8, 0x4b, 0xbc, 0xd8, 0xdf, 0x93, 0xf6, 0xa9, 0x35, 0x72, 0xad, 0xb1, 0x5e,
	0x53, 0xf1, 0x40, 0xf2, 0xa1, 0x98, 0xfd, 0x45, 0xa0, 0xb5, 0x21, 0xc4, 0xc3, 0x48, 0xf9, 0x5d,
	0xdf, 0x73, 0x95, 0x1f, 0x85, 0xf4, 0x06, 0xd4, 0x12, 0x19, 0x74, 0x4d, 0x34, 0x2e, 0x4d, 0xc5,
	0xc4, 0x51, 0x95, 0xbe, 0x0f, 0x0b, 0x1a, 0x96, 0x5d, 0x59, 0xab, 0x3e, 0xdb, 0xc8, 0x28, 0x53,
	0x0e, 0x4d, 0xb3, 0x53, 0x0a, 0xc3, 0x3b, 0x13, 0xac, 0x87, 0xaf, 0xbd, 0xa9, 0x25, 0x3a, 0x22,
	0x4b, 0x5e, 0x61, 0xc5, 0x7e, 0x22, 0x60, 0x99, 0xed, 0x4e, 0xd8, 0x8d, 0xe8, 0x2e, 0x58, 0x42,
	0xa6, 0xb7, 0xed, 0xa7, 0x97, 0xb3, 0x09, 0x9e, 0x70, 0x6b, 0xd6, 0x13, 0xee, 0x0f, 0x4d, 0x79,
	0xd1, 0xcf, 0x09, 0x6f, 0xcc, 0xfe, 0xae, 0xc2, 0xd9, 0xcd, 0x58, 0xba, 0x4a, 0x9a, 0x03, 0x32,
	0x1a, 0x7e, 0x00, 0xa7, 0x33, 0x1a, 0x1a, 0x46, 0x8d, 0x27, 0x63, 0xce, 0xa8, 0xa6, 0x21, 0xe3,
	0x04, 0x42, 0x55, 0xd0, 0xfa, 0xb9, 0x09, 0x35, 0xe6, 0x45, 0xc8, 0x9c, 0x2f, 0x42, 0x6f, 0x03,
	0x64, 0x3e, 0x91, 0xa5, 0x53, 0x73, 0x6c, 0xd1, 0xa8, 0x76, 0x44, 0x99, 0xdc, 0x29, 0x7f, 0x8b,
	0xe4, 0xbe, 0x0b, 0x56, 0x10, 0x79, 0x6e, 0xe0, 0x60, 0x18, 0xec, 0x85, 0xe9, 0x5e, 0x01, 0x75,
	0x37, 0x52, 0x55, 0xfa, 0x08, 0xa8, 0xb6, 0x2c, 0xc5, 0xab, 0x3e, 0x73, 0xbc, 0x96, 0xd1, 0xba,
	0x20, 0x61, 0x01, 0xac, 0x8e, 0xbc, 0x69, 0xd2, 0x8f, 0xc2, 0x64, 0x24, 0x3d, 0xc9, 0x48, 0x7a,
	0x96, 0xc3, 0x52, 0x99, 0x35, 0x2c, 0xec, 0x0b, 0x68, 0xdd, 0xf7, 0x93, 0x24, 0x0a, 0x0e, 0xe4,
	0x3c, 0x35, 0xec, 0x1c, 0x2c, 0xc4, 0xd2, 0x4d, 0xa2, 0x10, 0x8f, 0x6e, 0x72, 0xb3, 0x62, 0x4f,
	0x2b, 0x40, 0xb7, 0xfc, 0x50, 0x98, 0xbb, 0x7c, 0x8a, 0x74, 0x4f, 0x28, 0x03, 0x2b, 0x51, 0x6e,
	0xac, 0x1c, 0x3f, 0x14, 0xf2, 0x10, 0x4f, 0x69, 0xae, 0x93, 0x77, 0x39, 0xa0, 0xb4, 0x93, 0x0a,
	0xe9, 0x55, 0xb0, 0x7a, 0xee, 0xa1, 0x13, 0xcb, 0x64, 0x10, 0xa8, 0x44, 0xfb, 0x5d, 0xaf, 0xdc,
	0xb8, 0xcd, 0xa1, 0xe7, 0x1e, 0x72, 0x2d, 0xa5, 0x14, 0x6a, 0xa1, 0xdb, 0xd3, 0xc4, 0x5a, 0xe4,
	0xf8, 0x9b, 0xda, 0x50, 0xef, 0xc7, 0xd1, 0x7e, 0xec, 0xf6, 0x90, 0x1e, 0x75, 0x9e, 0x2d, 0x53,
	0x94, 0x18, 0x6e, 0x5d, 0xc0, 0xea, 0xdc, 0xac, 0xe8, 0x55, 0x68, 0x7a, 0x6e, 0xdf, 0xf5, 0x7c,
	0x75, 0xe4, 0x74, 0x07, 0x41, 0x80, 0x04, 0x68, 0xf2, 0xa5, 0x4c, 0xb8, 0x35, 0x08, 0x02, 0xda,
	0x81, 0x65, 0x57, 0xa9, 0xd8, 0xdf, 0x1b, 0x28, 0xe9, 0x74, 0xfd, 0x40, 0xc9, 0xd8, 0xae, 0x63,
	0xfe, 0x5f, 0x1e, 0x09, 0xcf, 0x46, 0xa6, 0xb6, 0x85, 0x5a, 0xbc, 0xe5, 0x96, 0x05, 0xf4, 0x0a,
	0x64, 0x9c, 0x76, 0xd4, 0x51, 0x5f, 0xda, 0x0d, 0x44, 0x6f, 0x19, 0xd9, 0x67, 0x47, 0x7d, 0xc9,
	0x7e, 0x24, 0xa5, 0xc0, 0xbd, 0xa8, 0xc4, 0xde, 0x84, 0x7a, 0xa4, 0xdf, 0xc0, 0xf4, 0x98, 0xb7,
	0x26, 0x70, 0xf4, 0xf8, 0xa3, 0xf1, 0xcc, 0x92, 0x09, 0x58, 0x29, 0x41, 0x33, 0xfc, 0xdc, 0x86,
	0xba, 0xb1, 0xb6, 0x09, 0x56, 0xb1, 0x13, 0xd5, 0xc5, 0xcc, 0x07, 0x5b, 0x85, 0x95, 0x8f, 0xa4,
	0xca, 0x8a, 0xaf, 0x30, 0x11, 0x60, 0x0f, 0xe1, 0x6c, 0x59, 0x6c, 0x4e, 0x2f, 0x27, 0x00, 0x99,
	0x39, 0x01, 0xfe, 0x21, 0xb0, 0x5a, 0x70, 0x18, 0x76, 0xa3, 0x79, 0xf2, 0x60, 0x34, 0x0d, 0x2b,
	0x33, 0x56, 0xa7, 0x37, 0xc1, 0xea, 0x4a, 0xe5, 0x3d, 0x2e, 0xd4, 0xc9, 0xc6, 0xfa, 0xa9, 0xae,
	0x1b, 0x24, 0x92, 0x03, 0xee, 0xe8, 0xea, 0xf7, 0x36, 0x34, 0xb5, 0x9e, 0x2e, 0x37, 0x09, 0x32,
	0x3c, 0xd7, 0x5c, 0xc2, 0x3d, 0x5d, 0x4c, 0x12, 0xe6, 0xc0, 0xb9, 0xd1, 0x8b, 0x99, 0x58, 0x3d,
	0x18, 0xf2, 0xcf, 0x0f, 0xbb, 0x91, 0xb9, 0xdd, 0xa4, 0x72, 0x55, 0xf4, 0x90, 0x71, 0x34, 0x5d,
	0xb0, 0x7f, 0x2b, 0x40, 0x3f, 0x8e, 0xfc, 0xf0, 0xd5, 0x6c, 0x3e, 0xe5, 0xa7, 0xa8, 0xce, 0xfc,
	0x14, 0x53, 0xa7, 0xa0, 0x4d, 0x38, 0xd3, 0x8d, 0x7d, 0x19, 0x0a, 0xc7, 0xf5, 0xbc, 0x68, 0x10,
	0x9a, 0x6e, 0x52, 0x9d, 0xe6, 0xbb, 0xa5, 0x2d, 0x36, 0xb4, 0x41, 0x47, 0xd0, 0xeb, 0xa0, 0xab,
	0xbe, 0x93, 0x4f, 0x4e, 0x31, 0x56, 0x9c, 0x6c, 0xa2, 0x6a, 0xe1, 0xee, 0x4e, 0xbe, 0xc9, 0xfe,
	0x24, 0xb0, 0x52, 0x0a, 0xf4, 0xf8, 0x8e, 0x50, 0xee, 0x69, 0x1b, 0x70, 0x21, 0x96, 0x4f, 0x06,
	0x7e, 0x2c, 0x1d, 0x03, 0xf9, 0xc0, 0x0d, 0x7c, 0x81, 0x53, 0x19, 0xc6, 0x34, 0xa7, 0xcd, 0x79,
	0xa3, 0xb7, 0x85, 0x6a, 0x9f, 0xe7, 0x5a, 0x74, 0x0b, 0x68, 0x3f, 0xf6, 0x0f, 0xfc, 0x40, 0xee,
	0xcb, 0xfc, 0xc6, 0x76, 0x75, 0xfa, 0x75, 0xcf, 0x0c, 0x4d, 0xcc, 0x95, 0x59, 0x07, 0x96, 0x53,
	0xf8, 0xa5, 0xb9, 0x70, 0x38, 0xf2, 0xe8, 0x21, 0x6a, 0xc6, 0x91, 0xe7, 0x3b, 0x02, 0x67, 0x3e,
	0x91, 0xee, 0x81, 0x2c, 0x39, 0x3b, 0x49, 0xaa, 0xbe, 0x07, 0x8b, 0xf9, 0xd8, 0xfd, 0xac, 0x4c,
	0x6d, 0x64, 0x03, 0x77, 0xa1, 0xd1, 0x55, 0x4b, 0x8d, 0xee, 0x2b, 0x58, 0xd0, 0x48, 0xe9, 0x2d,
	0x68, 0x14, 0x88, 0x3f, 0x75, 0x8e, 0xcf, 0x15, 0xe9, 0x5d, 0x38, 0x95, 0x91, 0x7d, 0xd6, 0xd1,
	0x5d, 0x1b, 0xa4, 0x33, 0xb7, 0xb5, 0x5d, 0xa2, 0xfd, 0x62, 0xde, 0x6e, 0x4c, 0x1d, 0xb6, 0x27,
	0xf5, 0x27, 0x3e, 0x54, 0xa5, 0xe7, 0xa0, 0x16, 0x47, 0x81, 0xc4, 0x01, 0xb4, 0xf9, 0x61, 0x65,
	0x99, 0x70, 0x5c, 0xd3, 0x2b, 0x00, 0xf9, 0x83, 0x26, 0x78, 0xe9, 0x1a, 0x76, 0xea, 0xa1, 0x90,
	0xb6, 0xa1, 0x86, 0x65, 0x44, 0x0f, 0x63, 0x17, 0x47, 0x4f, 0x33, 0xbc, 0x4f, 0xcb, 0x07, 0xea,
	0xd1, 0x4b, 0xb0, 0xf0, 0xd8, 0x17, 0x42, 0x86, 0xe6, 0x3b, 0xc2, 0xd0, 0xd0, 0x08, 0xd9, 0x2e,
	0xd4, 0xb7, 0x65, 0x92, 0xb8, 0xfb, 0x27, 0xbf, 0x0c, 0xcd, 0x2f, 0x93, 0xbe, 0x11, 0xfe, 0x66,
	0x3f, 0x10, 0x58, 0xe1, 0xb2, 0x17, 0x1d, 0xc8, 0xf9, 0x3f, 0xd9, 0x5e, 0x2c, 0x77, 0xbe, 0x27,
	0x40, 0x35, 0xb2, 0x57, 0x8c, 0xd4, 0xbf, 0x13, 0x38, 0xbf, 0x23, 0x43, 0x61, 0x9e, 0x63, 0x6e,
	0x74, 0x77, 0xa1, 0xde, 0xd3, 0xae, 0x0c, 0xb6, 0xcb, 0x13, 0x79, 0x8e, 0x5a, 0x3c, 0x53, 0xa7,
	0x37, 0x61, 0xc5, 0x14, 0x29, 0xe1, 0x8c, 0xa3, 0x23, 0xcd, 0x76, 0x1f, 0xe5, 0x9b, 0xec, 0x29,
	0x01, 0x5a, 0x40, 0x3f, 0xcf, 0x7b, 0xbf, 0x5c, 0xe0, 0xdf, 0x12, 0x68, 0xed, 0x48, 0xc5, 0xa3,
	0x40, 0x26, 0xf3, 0x0d, 0xe5, 0xe3, 0x53, 0xba, 0x44, 0x92, 0x67, 0x54, 0xf3, 0x9c, 0x24, 0xec,
	0x97, 0x94, 0x0c, 0x59, 0x4f, 0x1a, 0x69, 0xf9, 0x2f, 0x73, 0x54, 0x2a, 0x35, 0xbd, 0x6a, 0xb9,
	0x3f, 0xb3, 0x3b, 0x60, 0x1f, 0xc7, 0x38, 0x43, 0xb7, 0x64, 0x5f, 0x13, 0xb0, 0x77, 0xc3, 0xbc,
	0x21, 0xff, 0x4f, 0x25, 0x82, 0xfd, 0x4a, 0xe0, 0xf2, 0x6e, 0x5f, 0x0c, 0xbf, 0xfe, 0xb0, 0xa8,
	0xcf, 0x9d, 0x78, 0x8f, 0x60, 0x09, 0xbb, 0x85, 0x93, 0x86, 0x31, 0x27, 0xf1, 0x73, 0x7e, 0x87,
	0x5b, 0xe8, 0x62, 0x13, 0x3d, 0xb0, 0x9f, 0x09, 0x5c, 0x38, 0x0e, 0x74, 0x9e, 0x80, 0xbd, 0x78,
	0x8c, 0x7f, 0x10, 0xb8, 0xa4, 0x31, 0x16, 0x1a, 0xe4, 0xdc, 0xb1, 0xbc, 0x77, 0x0c, 0xe7, 0x0c,
	0xff, 0xb1, 0x29, 0xe2, 0xa2, 0x6f, 0xc0, 0x52, 0x8c, 0xe5, 0x5e, 0x38, 0x98, 0x9f, 0xd5, 0x3c,
	0x3f, 0x2d, 0x23, 0x4f, 0x53, 0x9f, 0xfd, 0x96, 0x52, 0x72, 0x14, 0xfe, 0x7c, 0xff, 0x68, 0x7c,
	0x39, 0xc8, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x9e, 0x6a, 0x60, 0xae, 0x15, 0x00, 0x00,
}
